"""生活流素材池 · A/B 卷：职场受挫、亲密关系与家庭重创、深夜代偿自愈、隐性内耗潜台词。

约定：
- 文本内使用 `{boss}` `{peer}` `{obj}` `{workplace}` `{city}` `{commute}` `{hr}` `{hrv}` 等占位符；
- 职场受挫素材按 domain 分域，避免“口腔耗材销售”跑进“宿舍查寝”这类场景错配；
- 亲密关系素材带 `requires` 标签（PARTNER / MARRIED / CHILD / PARENT / ANY），与人设婚恋状态匹配后才允许使用；
- 代偿自愈素材自带候选维度（第 73 条要素由 pools_dimensions 补全），供答卷提炼“反常代偿行为”。
"""

from __future__ import annotations

from typing import Any, Dict, List

# ---------------------------------------------------------------------------
# 职业域映射：职场受挫场景必须与人设职业同域
# ---------------------------------------------------------------------------
OCCUPATION_DOMAIN: Dict[str, str] = {
    "互联网后端架构师": "OFFICE",
    "互联网大厂产品经理": "OFFICE",
    "互联网数据分析师": "OFFICE",
    "游戏公司数值策划": "OFFICE",
    "电商平台运营主管": "OFFICE",
    "软件外包交付项目经理": "OFFICE",
    "财务共享中心总账会计": "FINANCE",
    "银行总行风险审查岗": "FINANCE",
    "城商行对公客户经理": "FINANCE",
    "国有银行网点柜员": "FINANCE",
    "小型律所执业律师": "FINANCE",
    "三甲医院麻醉科主治医师": "MEDICAL",
    "三甲医院急诊科护士": "MEDICAL",
    "三甲医院放射科技师": "MEDICAL",
    "社区医院全科医生": "MEDICAL",
    "乡镇卫生院公卫医师": "MEDICAL",
    "口腔科执业医师": "MEDICAL",
    "连锁药房执业药师": "MEDICAL",
    "宠物医院执业兽医师": "MEDICAL",
    "医疗器械售后工程师": "MEDICAL",
    "初中语文教师兼班主任": "EDU",
    "公立小学英语教师": "EDU",
    "初中化学教师": "EDU",
    "小学体育教师": "EDU",
    "幼儿园大班主班老师": "EDU",
    "高职院校辅导员": "EDU",
    "中职学校汽修实训教师": "EDU",
    "高校实验员": "EDU",
    "出版社图书编辑": "CREATIVE",
    "纪录片剪辑师": "CREATIVE",
    "自由插画师": "CREATIVE",
    "地方融媒体中心记者": "CREATIVE",
    "自由摄影师": "CREATIVE",
    "装修公司设计总监": "CREATIVE",
    "文旅项目策划": "CREATIVE",
    "汽车零部件销售经理": "SALES",
    "二手房产经纪人": "SALES",
    "生鲜超市采购主管": "SALES",
    "城市综合体招商主管": "SALES",
    "连锁餐饮门店店长": "SERVICE",
    "物业服务项目经理": "SERVICE",
    "养老机构护理主管": "SERVICE",
    "殡葬礼仪服务师": "SERVICE",
    "连锁药房": "SERVICE",
    "社区咖啡店店主": "SERVICE",
    "民航乘务长": "SERVICE",
    "地铁站值班站长": "SERVICE",
    "建筑工地项目经理": "FIELD",
    "货运司机": "FIELD",
    "电梯维保技师": "FIELD",
    "轨道交通信号检修工": "FIELD",
    "国有电网运维调度员": "FIELD",
    "城市环卫片区班长": "FIELD",
    "物流园区调度主管": "FIELD",
    "基层派出所社区民警": "FIELD",
    "国营施工图结构设计师": "OFFICE",
    "档案数字化项目经理": "OFFICE",
    "区级机关综合科科员": "GOV",
    "人民法院书记员": "GOV",
    "国企宣传干事": "GOV",
    "芯片封装工艺工程师": "FACTORY",
    "半导体测试工程师": "FACTORY",
    "家具厂数控开料工": "FACTORY",
    "五金厂车间班组长": "FACTORY",
    "服装厂版房主管": "FACTORY",
    "健身工作室私教": "SERVICE",
    "有机农场主理人": "FIELD",
    "跨境电商独立站卖家": "OFFICE",
    "英语同声传译": "CREATIVE",
    "民营医院": "MEDICAL",
}

# ---------------------------------------------------------------------------
# 职场受挫素材（40 条，按域）：当众丢脸 + 具体损失 + 无法辩解的处境
# ---------------------------------------------------------------------------
CAREER_SETBACKS: List[Dict[str, Any]] = [
    # ---------- OFFICE ----------
    {"domain": "OFFICE", "who": "{boss}", "setting": "核心评审会（参会 9 人）",
     "quote": "这份方案连最基本的容灾与回滚都没写，你怎么敢拿上来过会？",
     "kw": ["当众质疑", "方案被否", "专业能力受挫"], "impact": "方案被当场打回，要求两天内重做"},
    {"domain": "OFFICE", "who": "{boss}", "setting": "季度复盘会（全员在场）",
     "quote": "你的项目又延期了，我不要听原因，我要听结果。",
     "kw": ["问责", "延期", "当众"], "impact": "绩效评级被口头降一档，团队年终奖挂钩"},
    {"domain": "OFFICE", "who": "甲方对接人", "setting": "客户方会议室（双方团队十余人）",
     "quote": "你们交付的东西根本不能用，这个项目我们考虑换供应商。",
     "kw": ["客户施压", "否定交付", "丢单风险"], "impact": "被要求 24 小时给出补救方案"},
    {"domain": "OFFICE", "who": "{boss}", "setting": "站会（全组围在工位旁）",
     "quote": "这个线上事故你负全责，今晚写一份复盘报告出来。",
     "kw": ["事故担责", "公开点名", "加班"], "impact": "当晚需完成事故复盘，次日晨会宣讲"},
    {"domain": "OFFICE", "who": "{peer}", "setting": "周例会",
     "quote": "会上把你数据里的问题逐条念了出来，还补了一句“这不该犯”。",
     "kw": ["同事背刺", "公开拆台", "难堪"], "impact": "会后被要求重跑全部数据"},
    {"domain": "OFFICE", "who": "{boss}", "setting": "一对一谈话室",
     "quote": "公司要优化，你的岗位在下季度名单里，先给你透个风。",
     "kw": ["裁员暗示", "岗位不稳", "失业恐惧"], "impact": "开始偷偷更新简历"},
    # ---------- FINANCE ----------
    {"domain": "FINANCE", "who": "分管副行长", "setting": "全行经营分析会（投影大屏）",
     "quote": "你的对公存款完成率全行倒数第一，这个数字你自己看得下去吗？",
     "kw": ["指标垫底", "当众通报", "业绩羞辱"], "impact": "被要求一周内拿出补量方案"},
    {"domain": "FINANCE", "who": "高级合伙人", "setting": "合伙人会议（助理也在场）",
     "quote": "这案子客户要换人，你自己想想问题出在哪。",
     "kw": ["被撤换", "专业否定", "合伙资格存疑"], "impact": "案件提成归零，还要写检讨"},
    {"domain": "FINANCE", "who": "审计组负责人", "setting": "审计沟通会",
     "quote": "这笔账目差异你解释不清，明天就把材料交到稽核部。",
     "kw": ["合规压力", "追责", "通宵整改"], "impact": "被要求连夜补齐全部底稿"},
    {"domain": "FINANCE", "who": "网点主任", "setting": "晨会（全员列队）",
     "quote": "季末揽储任务你差一半，这个月绩效自己心里有数。",
     "kw": ["任务缺口", "公开挨批", "收入受损"], "impact": "绩效扣减，还得去街头拉存款"},
    {"domain": "FINANCE", "who": "审查部总经理", "setting": "授信审查会",
     "quote": "你这份审查意见前后矛盾，是要我们跟着你一起担责吗？",
     "kw": ["专业能力被质疑", "风险担责", "公开放大"], "impact": "项目重新审查，须当面向总经理汇报"},
    # ---------- MEDICAL ----------
    {"domain": "MEDICAL", "who": "科室主任", "setting": "早交班（全科医护都在）",
     "quote": "这份方案谁签的字？出了事谁负责？",
     "kw": ["当众问责", "医疗风险", "签字权受质疑"], "impact": "被要求重写方案并当面汇报"},
    {"domain": "MEDICAL", "who": "患者家属", "setting": "护士站走廊（其他病人围观）",
     "quote": "你们是不是把药弄错了？我要投诉你！",
     "kw": ["投诉威胁", "公开指责", "人格受辱"], "impact": "写事件经过报告，等待医务科调查"},
    {"domain": "MEDICAL", "who": "护士长", "setting": "抢救区（抢救刚结束）",
     "quote": "交接记录少了一项，这种低级错误还要我教你第几遍？",
     "kw": ["低级错误", "当众训斥", "专业自尊受损"], "impact": "当班结束后留堂重学交接规范"},
    {"domain": "MEDICAL", "who": "技师长", "setting": "CT 机房外候诊区",
     "quote": "预约排程全乱了，患者都在门口等着，你到底怎么安排的？",
     "kw": ["流程失控", "当众质问", "患者积压"], "impact": "加班重排全部预约"},
    {"domain": "MEDICAL", "who": "患者家属", "setting": "诊室门口（候诊人群围观）",
     "quote": "排了三个小时你就说这几句话？你们医生是不是都不看病？",
     "kw": ["医患对立", "被当众指责", "委屈无处说"], "impact": "被要求道歉并重新解释病情"},
    {"domain": "MEDICAL", "who": "院办检查组", "setting": "全院季度检查通报会",
     "quote": "你负责的病区台账缺项最多，全院倒数。",
     "kw": ["通报批评", "台账缺失", "职业评价受损"], "impact": "需在三天内补齐并整改"},
    # ---------- EDU ----------
    {"domain": "EDU", "who": "年级组长", "setting": "年级组办公室（一屋子老师在）",
     "quote": "你班平均分又是垫底，家长投诉都到我这里来了。",
     "kw": ["成绩垫底", "家长投诉", "当众点名"], "impact": "被要求写教学反思并家访重点学生"},
    {"domain": "EDU", "who": "教导主任", "setting": "公开课试讲教室（教研组全员旁听）",
     "quote": "这个教案逻辑是断的，你这样上课学生怎么可能听得懂？",
     "kw": ["专业被否定", "公开课失败", "教研组内丢脸"], "impact": "公开课被换人，需重新备课"},
    {"domain": "EDU", "who": "学生家长", "setting": "家长群（四十多名家长可见）",
     "quote": "老师，我孩子说你昨天当众凶他，你出来解释一下。",
     "kw": ["家长公开质问", "声誉受损", "无处申辩"], "impact": "需向年级组说明，并单独约谈家长"},
    {"domain": "EDU", "who": "学生处处长", "setting": "学工例会",
     "quote": "你负责的学生心理台账不全，真出事你担得起吗？",
     "kw": ["安全责任", "台账不全", "被迫背责"], "impact": "连夜补齐台账，逐一约谈学生"},
    {"domain": "EDU", "who": "实训处主任", "setting": "实训车间（学生都在）",
     "quote": "你带的选手市赛连名次都没进，今年的集训方案重写。",
     "kw": ["竞赛失利", "当众宣布", "努力被否定"], "impact": "集训方案推翻重做"},
    # ---------- CREATIVE ----------
    {"domain": "CREATIVE", "who": "总编导", "setting": "机房（全组在场）",
     "quote": "这条片子重剪第三遍了，你到底有没有在动脑子？",
     "kw": ["反复返工", "当众训斥", "创作被否定"], "impact": "当晚通宵重剪，交出第四版"},
    {"domain": "CREATIVE", "who": "编辑部主任", "setting": "选题会",
     "quote": "这稿子问题太多，先别出书了，作者那边你自己去解释。",
     "kw": ["选题被否", "声誉受损", "面对作者压力"], "impact": "需向作者致歉并重做整个方案"},
    {"domain": "CREATIVE", "who": "新闻部主任", "setting": "采编大厅",
     "quote": "你这篇报道的核心事实没核实清楚，撤稿，后果你自己承担。",
     "kw": ["撤稿", "职业失误", "公开担责"], "impact": "稿件撤下，月度考核降档"},
    {"domain": "CREATIVE", "who": "甲方客户", "setting": "项目群（双方十余人在）",
     "quote": "方案完全不是我要的感觉，钱我不能这么付。",
     "kw": ["甲方否稿", "尾款风险", "创作被否定"], "impact": "须免费重置方案并重新提交"},
    {"domain": "CREATIVE", "who": "品牌方市场负责人", "setting": "拍摄现场（模特与助理都在）",
     "quote": "这组片子拍成这样，你让我怎么跟总部交代？",
     "kw": ["现场被训", "专业受质疑", "尾款风险"], "impact": "当天必须重拍并额外承担场地费"},
    {"domain": "CREATIVE", "who": "会务项目经理", "setting": "同传间外（主办方就在旁边）",
     "quote": "嘉宾说下半场翻译跟不上，主办方要扣你一半费用。",
     "kw": ["专业被质疑", "报酬被扣", "当场难堪"], "impact": "半天劳动面临扣款，需现场复盘"},
    # ---------- SALES ----------
    {"domain": "SALES", "who": "销售总监", "setting": "销售例会（团队全员）",
     "quote": "连续两个月没开单，你是在等公司养你吗？",
     "kw": ["业绩羞辱", "当众点名", "收入危机"], "impact": "被下最后通牒，月底前必须出单"},
    {"domain": "SALES", "who": "客户采购负责人", "setting": "客户会议室",
     "quote": "你们报价比对手高三成，理由说不清楚就别来了。",
     "kw": ["比价失败", "被否", "专业不被信任"], "impact": "订单大概率要丢，需重新报价"},
    {"domain": "SALES", "who": "门店店长", "setting": "晨会（全店经纪人在场）",
     "quote": "这个月你的带看转化是店里最低，你自己说怎么办。",
     "kw": ["业绩垫底", "公开施压", "收入不稳"], "impact": "被要求自费印传单扫楼"},
    {"domain": "SALES", "who": "采购总监", "setting": "供应商大会",
     "quote": "这批货损耗率这么高，中间环节到底是谁的问题？",
     "kw": ["损耗追责", "公开质疑", "信任受损"], "impact": "供应商提出索赔，需内部解释"},
    {"domain": "SALES", "who": "招商总监", "setting": "招商复盘会",
     "quote": "主力店签约又黄了，这个季度你贡献了什么？",
     "kw": ["签约失败", "当众质问", "价值感崩塌"], "impact": "季度奖金清零，重新谈判"},
    # ---------- SERVICE ----------
    {"domain": "SERVICE", "who": "区域督导", "setting": "门店后厨通道（员工都在）",
     "quote": "同商圈三家店就你的营业额垫底，你到底在干什么？",
     "kw": ["业绩垫底", "当众训斥", "经营压力"], "impact": "被要求一周内出整改方案"},
    {"domain": "SERVICE", "who": "业主", "setting": "小区中庭（几十位业主围观）",
     "quote": "物业费我们交着，你们就是这么做事的？我要投诉到底！",
     "kw": ["当众被骂", "投诉威胁", "尊严受损"], "impact": "被要求上门道歉并连夜整改"},
    {"domain": "SERVICE", "who": "客舱经理", "setting": "客舱后服务间",
     "quote": "这道投诉已经记在你名下，自己写说明。",
     "kw": ["投诉记名", "考核风险", "委屈难辩"], "impact": "飞行结束后追加书面检讨"},
    {"domain": "SERVICE", "who": "家属", "setting": "护理楼层走廊（其他家属围观）",
     "quote": "我妈背上起红疹了，你们是不是根本没按流程护理？",
     "kw": ["家属质疑", "护理被否认", "当众受责"], "impact": "被要求调取护理记录并当面解释"},
    {"domain": "SERVICE", "who": "直属领导", "setting": "值班室",
     "quote": "这次乘客纠纷的处理你全程被动，通报里点了你的名字。",
     "kw": ["被通报", "处理失当", "职业自信受损"], "impact": "本月服务考评降档"},
    {"domain": "SERVICE", "who": "客户", "setting": "门店吧台前（顾客排队等着）",
     "quote": "这杯咖啡的味道完全不对，你们是不是换了豆子还想糊弄我？",
     "kw": ["当众质疑", "手艺被否定", "门店口碑受疑"], "impact": "免单重做，还要安抚后面排队的客人"},
    # ---------- FIELD ----------
    {"domain": "FIELD", "who": "总包负责人", "setting": "工地例会（施工队都在）",
     "quote": "这个工序返工两次，损失算谁的？你项目经理怎么管的？",
     "kw": ["返工追责", "当众问责", "管理能力被否"], "impact": "被扣当月管理奖，须连夜赶工"},
    {"domain": "FIELD", "who": "车队调度", "setting": "货运群里（所有司机可见）",
     "quote": "这单又超时了，罚款从你运费里扣，别怪公司不讲情面。",
     "kw": ["超时罚款", "公开点名", "收入受损"], "impact": "运费被扣，还得自己垫油费"},
    {"domain": "FIELD", "who": "值班长", "setting": "调度大厅（交接班现场）",
     "quote": "你昨晚那条负荷曲线判断错了，差点造成越限，责任你自己清楚。",
     "kw": ["判断失误", "安全责任", "当众通报"], "impact": "写入值班记录，需参加安全复训"},
    {"domain": "FIELD", "who": "维保站长", "setting": "楼宇机房（业委会代表在场）",
     "quote": "电梯困人三十五分钟，你们维保是怎么做的？",
     "kw": ["事故问责", "当众质问", "职业资格受疑"], "impact": "年检整改工单全部重做，暂停接单一周"},
    {"domain": "FIELD", "who": "运营经理", "setting": "分拨中心现场（叉车司机都在）",
     "quote": "爆仓了你才说预案不够？这批货延误的钱你来赔吗？",
     "kw": ["预案失职", "当众施压", "赔偿风险"], "impact": "通宵调度并提交事故说明"},
    {"domain": "FIELD", "who": "带班副所长", "setting": "辖区警务室",
     "quote": "那起邻里纠纷你调解了三次还没结，群众电话都打到所里了。",
     "kw": ["调解失败", "群众投诉", "能力被质疑"], "impact": "被要求重新上门调解并留档"},
    {"domain": "FIELD", "who": "环卫所所长", "setting": "迎检动员会（全所都在）",
     "quote": "你片区被通报了两处卫生死角，这次功劳簿上没你。",
     "kw": ["被通报", "当众点名", "辛苦被抹"], "impact": "加班清理死角，取消当月评优"},
    {"domain": "FIELD", "who": "合作社负责人", "setting": "大棚外（农工都在）",
     "quote": "这批菜退货了一半，损失我认，你这份心思我也看明白了。",
     "kw": ["退货损失", "信任动摇", "经营受挫"], "impact": "当月订单削减，需自行承担损耗"},
    # ---------- GOV ----------
    {"domain": "GOV", "who": "{boss}", "setting": "科室例会（分管领导在场）",
     "quote": "这份材料连基本数据都对不上，你们综合科是怎么把关的？",
     "kw": ["材料被当众退回", "把关能力被质疑", "颜面受挫"],
     "impact": "材料被当众退回，要求当天重写并重新走流程"},
    {"domain": "GOV", "who": "承办法官", "setting": "审判庭办公区",
     "quote": "这份笔录关键处漏记了，案子要是因为这个被发回，你负得起这个责任吗？",
     "kw": ["关键失误", "责任追究", "当众被训"],
     "impact": "被要求连夜补记并接受庭内通报提醒"},
    {"domain": "GOV", "who": "宣传部长", "setting": "部务会（全部同事在场）",
     "quote": "这篇稿子被上面点名批评，你写的时候到底有没有看文件？",
     "kw": ["被上级点名", "稿件被批", "公开难堪"],
     "impact": "稿件全网撤下，年度考评记录一次失误"},
    {"domain": "GOV", "who": "带班副所长", "setting": "派出所值班室",
     "quote": "那个群众投诉又回到我们头上了，你自己去解释。",
     "kw": ["群众投诉", "重复追责", "无处申辩"],
     "impact": "被要求上门解释并重做台账"},
    {"domain": "EDU", "who": "园长", "setting": "家长开放日（全班家长与老师在场）",
     "quote": "孩子磕了一下你们都不知道，这个班的看护是怎么做的？",
     "kw": ["看护失职", "当众质问", "家长围观"], "impact": "被要求向家长逐一说明并提交事件报告"},
    {"domain": "EDU", "who": "课题组教授", "setting": "实验室组会",
     "quote": "这批数据重复不出来，你这两个月到底做了什么？",
     "kw": ["数据不可复现", "当众质疑", "成果被否定"], "impact": "实验全部重做，月底前交不出进展就换人"},
    {"domain": "SERVICE", "who": "服务部主管", "setting": "告别厅后场（同事都在）",
     "quote": "家属连流程都没被告知清楚，这个投诉你自己去解释。",
     "kw": ["流程投诉", "当众挨批", "职业尊严"], "impact": "被要求连夜重写服务流程并当面致歉"},
    {"domain": "SERVICE", "who": "工作室老板", "setting": "训练区（会员就在旁边）",
     "quote": "你的续课率是全店最低，这个月排课先砍掉一半。",
     "kw": ["续课垫底", "当着会员被训", "收入锐减"], "impact": "排课被砍，收入直接缩水四成"},
    {"domain": "FIELD", "who": "工班长", "setting": "检修库（同班组员都在）",
     "quote": "这处隐患你排查了一周还在，联锁测试出了问题算谁的？",
     "kw": ["隐患未除", "当众问责", "安全责任"], "impact": "被要求连夜复测全部道岔信号并写检查"},
    {"domain": "FACTORY", "who": "生产主管", "setting": "冲压车间（机组都在）",
     "quote": "你班组这个月的不良率又超了，奖金的事你自己心里有数。",
     "kw": ["不良率超标", "当众点名", "收入受损"], "impact": "当月班组奖金被扣，须提交整改计划"},
    {"domain": "MEDICAL", "who": "院长", "setting": "诊疗室（客户就在旁边等着）",
     "quote": "这例手术方案你怎么定的？客户在这里等了两个小时，你出来解释。",
     "kw": ["方案被质疑", "当着客户挨批", "专业受挫"], "impact": "被要求当场重新评估并当面致歉"},
    {"domain": "MEDICAL", "who": "设备科主任", "setting": "医院设备科（临床科室来催机）",
     "quote": "这台设备停了三天还没修好，手术排期都乱了，你到底什么时候能搞定？",
     "kw": ["停机追责", "当众催促", "专业被质疑"], "impact": "被要求当晚给出修复方案并驻场待命"},
    # ---------- FACTORY ----------
    {"domain": "FACTORY", "who": "工艺组长", "setting": "车间早会（全组都在）",
     "quote": "良率掉成这样你还在解释什么？先把报告写出来。",
     "kw": ["良率事故", "当众训斥", "被要求担责"], "impact": "连夜分析原因，次日上交报告"},
    {"domain": "FACTORY", "who": "生产厂长", "setting": "版房（设计师都在）",
     "quote": "这批样衣尺寸全错了，秋冬款还上不上？",
     "kw": ["批量出错", "当众质问", "交期压力"], "impact": "通宵重出版单，交期压缩"},
    {"domain": "FACTORY", "who": "车间主任", "setting": "生产车间（机器声里）",
     "quote": "你班组的排产又插错了单，客户那边已经投诉到厂里。",
     "kw": ["排产失误", "客户投诉", "当众批评"], "impact": "当班产量扣减，需重排全部订单"},
    {"domain": "FACTORY", "who": "测试经理", "setting": "测试车间外办公室",
     "quote": "程式优化拖了三周还没结果，测试产能卡在你这里了。",
     "kw": ["进度滞后", "产能卡点", "专业受质疑"], "impact": "被要求周末加班完成验证"},
]


# ---------------------------------------------------------------------------
# 亲密关系 / 家庭重创（32 条）：requires 控制与人设婚恋状态的匹配
# ---------------------------------------------------------------------------
CRISIS_MOTIFS: List[Dict[str, Any]] = [
    {"label": "伴侣提出分手", "requires": "PARTNER", "channel": "微信",
     "text": "伴侣发来一句：“我们分手吧，我累了。周末我把东西搬走，别找我了。”随后头像变成灰色。",
     "kw": ["分手", "关系破裂", "毫无预兆"], "axis": "RELATION",
     "mechanism": "亲密关系被单方面终止，叠加白天职场受挫形成情绪叠加打击"},
    {"label": "伴侣指责不理解", "requires": "PARTNER", "channel": "电话",
     "text": "伴侣打来电话，语气疲惫：“你心里只有工作，我们这样下去还有意思吗？”话没说完就挂断了。",
     "kw": ["关系疏离", "被指责缺席", "沟通断裂"], "axis": "RELATION",
     "mechanism": "白天的职业挫败感被亲密关系的指责再次放大，形成双向否定"},
    {"label": "离婚协议", "requires": "MARRIED", "channel": "当面",
     "text": "伴侣把一份签好字的离婚协议放在餐桌上，只说了一句“你抽空看看”，然后回了卧室，关上门。",
     "kw": ["离婚", "家庭破裂", "沉默对峙"], "axis": "RELATION",
     "mechanism": "婚姻濒临解体，白天的职业压力失去最后的情感缓冲"},
    {"label": "订婚变故", "requires": "PARTNER", "channel": "电话",
     "text": "伴侣的母亲打来电话，语气客气而疏远：“孩子们的事我们再想想，彩礼和房子的事先缓缓吧。”",
     "kw": ["婚事受阻", "被否定", "家庭矛盾"], "axis": "RELATION",
     "mechanism": "婚恋前景被对方家庭单方面冻结，与职场挫败叠加造成价值感受损"},
    {"label": "异地关系终结", "requires": "PARTNER", "channel": "微信",
     "text": "伴侣发来长消息：“两年了，我们谁都不肯让步。我不想再这样耗下去了，就这样吧。”",
     "kw": ["异地终结", "长期耗竭", "关系破裂"], "axis": "RELATION",
     "mechanism": "长期异地关系中积累的耗竭被一次性引爆，与白天受挫形成连锁"},
    {"label": "伴侣病倒", "requires": "MARRIED", "channel": "电话",
     "text": "伴侣在电话里声音发虚：“我在医院，医生说让家属过来一趟。”",
     "kw": ["伴侣病倒", "未知病情", "责任感骤增"], "axis": "FAMILY",
     "mechanism": "伴侣健康出现不确定信号，家庭照护责任瞬间压到本人身上"},
    {"label": "孩子在校出事", "requires": "CHILD", "channel": "电话",
     "text": "孩子的班主任打来电话：“孩子今天在学校和同学发生冲突，对方家长要求当面谈，你尽快来一趟。”",
     "kw": ["孩子出事", "学校召见", "父母责任"], "axis": "FAMILY",
     "mechanism": "子女突发的学校事件把工作与家庭的双重角色同时逼到临界"},
    {"label": "孩子成绩崩塌", "requires": "CHILD", "channel": "微信",
     "text": "孩子的补习老师发来消息：“这次模拟考又退了一百多名，孩子最近状态很不对劲。”",
     "kw": ["孩子退步", "教育焦虑", "失职自责"], "axis": "FAMILY",
     "mechanism": "子女教育问题触发父母角色的失职感，与职场挫败形成自责叠加"},
    {"label": "母亲住院", "requires": "PARENT", "channel": "电话",
     "text": "姐姐打来电话，声音压得很低：“妈今天住院了，医生说要做进一步检查，你先别慌。”",
     "kw": ["长辈住院", "检查未明", "心理悬置"], "axis": "FAMILY",
     "mechanism": "长辈健康不确定性带来的牵挂与无力感，在白天受挫后集中爆发"},
    {"label": "父亲检查异常", "requires": "PARENT", "channel": "微信",
     "text": "父亲发来一张检查单照片，只写了四个字：“医生说没事。”但报告单上一栏被标了红色箭头。",
     "kw": ["报告异常", "家人隐瞒", "未知恐惧"], "axis": "FAMILY",
     "mechanism": "长辈刻意轻描淡写反而放大不安，形成持续性心理悬置"},
    {"label": "老家遭灾", "requires": "ANY", "channel": "电话",
     "text": "老家的亲戚打来电话：“你家老房子后墙塌了半边，人没事，但东西泡了不少。”",
     "kw": ["财产损失", "老家变故", "分身乏术"], "axis": "FAMILY",
     "mechanism": "突发财产损失与地理隔离带来的无力感叠加在职业压力之上"},
    {"label": "弟弟借钱", "requires": "ANY", "channel": "微信",
     "text": "弟弟发来消息：“哥/姐，我这边出了点事，能不能先借我三万，我下个月一定还。”",
     "kw": ["亲属借钱", "边界被侵犯", "金钱压力"], "axis": "FINANCE",
     "mechanism": "亲属的金钱请求打破个人财务边界，与既有月供压力形成叠加"},
    {"label": "房贷逾期预警", "requires": "ANY", "channel": "短信",
     "text": "银行短信提示：本月房贷扣款余额不足，请在 3 日内补足，逾期将计收罚息并影响征信。",
     "kw": ["资金缺口", "征信风险", "紧迫感"], "axis": "FINANCE",
     "mechanism": "刚性月供出现漏洞，经济安全感的根基被动摇"},
    {"label": "公司欠薪", "requires": "ANY", "channel": "微信",
     "text": "同事在群里说：“这个月工资又拖了，HR 只说再等等。”消息发出一分钟就被撤回。",
     "kw": ["欠薪", "收入不稳", "无助"], "axis": "FINANCE",
     "mechanism": "收入来源的不确定性直接冲击家庭现金流预期"},
    {"label": "合伙纠纷", "requires": "ANY", "channel": "电话",
     "text": "合伙人打来电话：“账上那笔钱我拿去周转了，你先别问，反正分红少不了你的。”",
     "kw": ["信任崩塌", "资金被挪用", "经营风险"], "axis": "FINANCE",
     "mechanism": "合伙人越界操作击穿信任底线，叠加职场受挫造成失控感"},
    {"label": "长辈催婚催生", "requires": "PARTNER", "channel": "电话",
     "text": "母亲在电话里叹气：“你看看别人家的孩子，你们到底打算什么时候要孩子？”",
     "kw": ["代际冲突", "被催促", "无法反驳"], "axis": "FAMILY",
     "mechanism": "代际期望与个人现实错位，常年积累的愧疚在疲惫时集中翻涌"},
    {"label": "配偶失业", "requires": "MARRIED", "channel": "当面",
     "text": "伴侣回到家，把包放下说：“我今天办完离职了。先别问，让我静一静。”",
     "kw": ["家庭收入腰斩", "重担压身", "沉默"], "axis": "FINANCE",
     "mechanism": "家庭经济支柱角色骤然唯一化，与职场挫败形成叠加压力"},
    {"label": "旧伤被提起", "requires": "PARTNER", "channel": "当面",
     "text": "争执中伴侣脱口而出：“当年要不是你非要这样，我们至于过成现在这样吗？”",
     "kw": ["旧事重提", "被指责", "情绪失控"], "axis": "RELATION",
     "mechanism": "亲密关系中的旧账被翻出，白天的职业挫败感找到情绪出口"},
    {"label": "相亲被否", "requires": "ANY", "channel": "微信",
     "text": "介绍人发来消息：“对方说你条件还行，就是工作太忙顾不了家，这事就先这样吧。”",
     "kw": ["被挑剔", "否定感", "婚恋焦虑"], "axis": "RELATION",
     "mechanism": "婚恋评价直接指向本人的工作与生活方式，与职业受挫形成同向打击"},
    {"label": "父母冷战", "requires": "PARENT", "channel": "电话",
     "text": "母亲在电话里低声说：“你爸这两天都不跟我说话，家里冷得像冰窖，你别管。”",
     "kw": ["家庭冷战", "夹在中间", "无能为力"], "axis": "FAMILY",
     "mechanism": "原生家庭的紧张关系让本人既无法介入也无法抽身"},
    {"label": "宠物离世", "requires": "ANY", "channel": "当面",
     "text": "回到家发现陪伴八年的猫趴在窝里已经没有了呼吸，姿势像是睡着。",
     "kw": ["丧失", "陪伴终结", "孤独感"], "axis": "RELATION",
     "mechanism": "唯一无条件陪伴的丧失在受挫当天形成叠加性的失落"},
    {"label": "体检复查通知", "requires": "ANY", "channel": "电话",
     "text": "体检中心来电：“您的一項指标需要复查，建议尽快预约，具体我们见面说。”",
     "kw": ["自身健康未知", "不确定感", "恐惧"], "axis": "FAMILY",
     "mechanism": "自身健康的不确定信号叠加在职业与人际压力之上"},
    {"label": "闺蜜/好友绝交", "requires": "ANY", "channel": "微信",
     "text": "多年好友发来一句：“我发现我们其实根本不是一路人，以后就别联系了。”",
     "kw": ["友谊破裂", "支持系统受损", "被否定"], "axis": "RELATION",
     "mechanism": "核心社会支持系统的断裂让情绪失去最后的缓冲带"},
    {"label": "房东要卖房", "requires": "ANY", "channel": "微信",
     "text": "房东发来消息：“房子下个月我要挂出去卖，你月底前搬走，押金退你。”",
     "kw": ["居所不稳", "被迫搬迁", "失控感"], "axis": "FAMILY",
     "mechanism": "居住稳定性被外部决定，生活掌控感进一步流失"},
    {"label": "孩子被欺负", "requires": "CHILD", "channel": "电话",
     "text": "伴侣打来电话，声音发抖：“孩子在学校被几个同学堵了，脸上有伤，我刚到学校。”",
     "kw": ["孩子受伤", "愤怒", "无法立即到场"], "axis": "FAMILY",
     "mechanism": "子女受伤害激起的愤怒与无力感，在没有现场介入能力时转为自责"},
    {"label": "母亲旧病复发", "requires": "PARENT", "channel": "电话",
     "text": "父亲打来电话：“你妈老毛病又犯了，这次疼得厉害，一直不肯去医院。”",
     "kw": ["长辈病情反复", "劝说无效", "牵挂"], "axis": "FAMILY",
     "mechanism": "长辈健康问题反复出现，长期的照护焦虑在受挫日集中释放"},
    {"label": "被裁传闻", "requires": "ANY", "channel": "电话",
     "text": "前同事打来电话：“听说你们部门要被整合，你那边情况怎么样？有消息记得跟我说。”",
     "kw": ["失业恐惧", "前途未卜", "无处求证"], "axis": "FINANCE",
     "mechanism": "职业稳定性出现不确定信号，与当天的当众受挫形成同频共振"},
    {"label": "亲戚借钱", "requires": "ANY", "channel": "电话",
     "text": "多年不联系的亲戚突然来电：“听说你现在混得不错，我这边急用五万，你帮衬一下。”",
     "kw": ["人情绑架", "金钱边界", "两难"], "axis": "FINANCE",
     "mechanism": "人情与金钱的双重压力让本已紧绷的财务心理再次告急"},
    {"label": "配偶冷战升级", "requires": "MARRIED", "channel": "当面",
     "text": "伴侣整晚没有说一句话，只在睡前发来一条微信：“你什么时候能陪我说说话？”",
     "kw": ["冷暴力", "情感饥渴", "内疚"], "axis": "RELATION",
     "mechanism": "亲密关系中的情感真空与职场挫败叠加，形成双重耗竭"},
    {"label": "亲人手术风险", "requires": "PARENT", "channel": "电话",
     "text": "哥哥打来电话：“明天爸做手术，医生说有风险，让你最好能回来一趟。”",
     "kw": ["手术风险", "必须到场", "分身乏术"], "axis": "FAMILY",
     "mechanism": "必须到场而难以到场，形成强烈的道义压力与自责"},
    {"label": "长辈被骗", "requires": "PARENT", "channel": "电话",
     "text": "母亲支支吾吾地说：“我昨天把银行卡号和短信验证码给了个自称公安局的，你爸知道了跟我吵了一架。”",
     "kw": ["长辈受骗", "家庭争执", "追责压力"], "axis": "FINANCE",
     "mechanism": "长辈遭遇诈骗带来的资金风险与家庭内部指责叠加"},
    {"label": "伴侣提分开冷静", "requires": "PARTNER", "channel": "微信",
     "text": "伴侣发来消息：“我们先分开一段时间吧，我需要想清楚。手机我不会关机，但别一直找我。”",
     "kw": ["关系悬置", "不确定", "焦虑"], "axis": "RELATION",
     "mechanism": "关系被悬置在不确定状态，比明确结束更持续地消耗情绪资源"},
]


# ---------------------------------------------------------------------------
# 深夜代偿自愈（26 条）：反常但具建设性的自我修复行为 + 候选维度
# ---------------------------------------------------------------------------
COPING_MOTIFS: List[Dict[str, Any]] = [
    {"label": "刷算法题", "category": "STRESS_INTELLECTUAL_COPING",
     "dimension_id": "dim:candidate_stress_intellectual_coping",
     "dimension_name": "逆境下智力代偿与心流解压倾向",
     "timeline": "开始一个人刷算法题，连做了六道动态规划题，写完最后一道时靠在椅背上长出了一口气",
     "app": "VS Code", "kind": "HOBBY", "source": "APP",
     "evidence_kw": ["刷题", "算法", "心流", "未向任何人提及"],
     "recovery": "刷题期间心率平稳回落至 74bpm，情绪压力指数下行"},
    {"label": "拼装模型", "category": "STRESS_HANDCRAFT_FLOW",
     "dimension_id": "dim:candidate_stress_handcraft_flow",
     "dimension_name": "逆境下手作心流修复倾向",
     "timeline": "从柜子深处翻出拼装模型，一个人拼到凌晨，把零件一片片对准卡扣按进去",
     "app": "B站", "kind": "HOBBY", "source": "SENSOR",
     "evidence_kw": ["拼装", "手工", "专注", "独处"],
     "recovery": "拼装过程中呼吸频率趋稳，皮温回升 0.9℃"},
    {"label": "深夜练琴", "category": "STRESS_RHYTHMIC_SENSORY",
     "dimension_id": "dim:candidate_stress_rhythmic_sensory",
     "dimension_name": "逆境下节律感官代偿倾向",
     "timeline": "坐到琴前练了两个小时音阶，反复把同一段练习曲放慢到 60 拍，直到手指记住为止",
     "app": None, "kind": "HOBBY", "source": "SENSOR",
     "evidence_kw": ["练琴", "节律", "重复", "沉浸"],
     "recovery": "练琴后半段心率稳定在 72bpm，压力指数持续下行"},
    {"label": "深夜长跑", "category": "STRESS_PHYSICAL_DISCHARGE",
     "dimension_id": "dim:candidate_stress_physical_discharge",
     "dimension_name": "逆境下高强度体能耗散倾向",
     "timeline": "换鞋出门，在江边跑了 8 公里，配速比平时快，跑完在堤坝上坐了很久",
     "app": "运动 APP", "kind": "ACTIVITY", "source": "SENSOR",
     "evidence_kw": ["夜跑", "体能耗散", "独处", "配速异常"],
     "recovery": "跑后 30 分钟心率回落至 88bpm，情绪压力指数明显下降"},
    {"label": "整理相册", "category": "STRESS_NOSTALGIC_SOOTHE",
     "dimension_id": "dim:candidate_stress_nostalgic_soothe",
     "dimension_name": "逆境下怀旧安抚倾向",
     "timeline": "把手机相册从头翻到尾，把三年前的老照片一张张放进新相簿，还给几张配了字",
     "app": "相册", "kind": "HOBBY", "source": "APP",
     "evidence_kw": ["相册", "怀旧", "回顾", "自我安抚"],
     "recovery": "翻相册期间心率平稳，后半夜情绪压力指数回落 41%"},
    {"label": "照料植物", "category": "STRESS_LIFE_CULTIVATION_COPING",
     "dimension_id": "dim:candidate_stress_life_cultivation",
     "dimension_name": "逆境下照料生命式意义重建倾向",
     "timeline": "在阳台把 12 盆多肉全部脱盆、修根、换土、重新上盆，一盆一盆摆好",
     "app": None, "kind": "HOBBY", "source": "SENSOR",
     "evidence_kw": ["植物", "照料", "重建", "秩序感"],
     "recovery": "换盆期间心率稳定在 72bpm，情绪压力指数下行，指纹皮温回升"},
    {"label": "手写长信", "category": "STRESS_WRITING_EXTERNALIZE",
     "dimension_id": "dim:candidate_stress_writing_externalize",
     "dimension_name": "逆境下书写外化情绪调节倾向",
     "timeline": "在笔记本上手写了四页东西，写完把它撕下来折好，压进抽屉最底层",
     "app": None, "kind": "NOTE", "source": "SENSOR",
     "evidence_kw": ["书写", "外化", "私密", "不示人"],
     "recovery": "书写后心率由 96bpm 回落至 78bpm，呼吸频率趋稳"},
    {"label": "整理房间", "category": "STRESS_CONTROL_REBUILD",
     "dimension_id": "dim:candidate_stress_control_rebuild",
     "dimension_name": "逆境下掌控感重建倾向",
     "timeline": "把衣柜、书桌、厨房台面依次整理了一遍，所有东西按尺寸重新归位，连数据线都重新绑好",
     "app": None, "kind": "LIFE", "source": "SENSOR",
     "evidence_kw": ["收纳", "秩序", "掌控感", "重复动作"],
     "recovery": "整理过程中动作放缓，心率逐步回落"},
    {"label": "研究古典密码", "category": "STRESS_INTELLECTUAL_COPING",
     "dimension_id": "dim:candidate_stress_intellectual_coping",
     "dimension_name": "逆境下智力代偿与心流解压倾向",
     "timeline": "翻出维吉尼亚密码的资料，用笔算了两个小时的字频表，最后把自己写的一小段话加密成了密文",
     "app": None, "kind": "NOTE", "source": "SENSOR",
     "evidence_kw": ["智力活动", "推演", "心流", "自足"],
     "recovery": "推演期间心率稳定在 73bpm，压力指数缓慢下行"},
    {"label": "做木工", "category": "STRESS_HANDCRAFT_FLOW",
     "dimension_id": "dim:candidate_stress_handcraft_flow",
     "dimension_name": "逆境下手作心流修复倾向",
     "timeline": "在阳台把一块废木料刨平、打磨、上蜡，做成一个巴掌大的小托盘",
     "app": None, "kind": "HOBBY", "source": "SENSOR",
     "evidence_kw": ["木工", "手作", "打磨", "成品"],
     "recovery": "打磨期间心率与皮温同步回稳，压力指数下降 35%"},
    {"label": "深夜做饭", "category": "STRESS_LIFE_CULTIVATION_COPING",
     "dimension_id": "dim:candidate_stress_life_cultivation",
     "dimension_name": "逆境下照料生命式意义重建倾向",
     "timeline": "凌晨和面、剁馅、包了两屉饺子，煮好后自己吃了一小碗，剩下的全部装盒冻进冰箱",
     "app": None, "kind": "LIFE", "source": "SENSOR",
     "evidence_kw": ["做饭", "照料", "储备", "规律动作"],
     "recovery": "包饺子期间心率平稳，情绪压力指数明显下降"},
    {"label": "给旧物保养", "category": "STRESS_HANDCRAFT_FLOW",
     "dimension_id": "dim:candidate_stress_handcraft_flow",
     "dimension_name": "逆境下手作心流修复倾向",
     "timeline": "把穿了五年的皮鞋拿出来，一步步清洁、上油、抛光，然后整齐摆回鞋柜",
     "app": None, "kind": "LIFE", "source": "SENSOR",
     "evidence_kw": ["保养", "旧物", "秩序", "专注"],
     "recovery": "保养期间心率较峰值回落 22bpm，呼吸平稳"},
    {"label": "背词磨耳朵", "category": "STRESS_INTELLECTUAL_COPING",
     "dimension_id": "dim:candidate_stress_intellectual_coping",
     "dimension_name": "逆境下智力代偿与心流解压倾向",
     "timeline": "戴着耳机把当日要背的六十个外语单词过了一遍，又在纸上默写了两轮",
     "app": "背单词 APP", "kind": "HOBBY", "source": "APP",
     "evidence_kw": ["背单词", "自我提升", "心流", "可量化"],
     "recovery": "背词期间心率稳定在 75bpm，压力指数下行"},
    {"label": "深夜跑步机", "category": "STRESS_PHYSICAL_DISCHARGE",
     "dimension_id": "dim:candidate_stress_physical_discharge",
     "dimension_name": "逆境下高强度体能耗散倾向",
     "timeline": "在客厅铺开垫子，做了 200 个卷腹与三组静力支撑，直到手臂发抖才停",
     "app": None, "kind": "ACTIVITY", "source": "SENSOR",
     "evidence_kw": ["体能", "力竭", "耗散", "自控"],
     "recovery": "运动后 40 分钟心率回落至 82bpm，皮温回升"},
    {"label": "抄经", "category": "STRESS_RITUAL_CALM",
     "dimension_id": "dim:candidate_stress_ritual_calm",
     "dimension_name": "逆境下仪式化静心代偿倾向",
     "timeline": "洗手、焚香、铺纸，用毛笔把同一段经文抄了两遍，一笔一划写完才收笔",
     "app": None, "kind": "NOTE", "source": "SENSOR",
     "evidence_kw": ["仪式", "抄经", "静心", "节律"],
     "recovery": "抄经期间心率降至 68bpm，HRV 回升至 42ms"},
    {"label": "拼图", "category": "STRESS_RITUAL_CALM",
     "dimension_id": "dim:candidate_stress_ritual_calm",
     "dimension_name": "逆境下仪式化静心代偿倾向",
     "timeline": "把 1000 片的拼图倒在地上，按色块分堆，一块一块拼到凌晨两点",
     "app": None, "kind": "HOBBY", "source": "SENSOR",
     "evidence_kw": ["拼图", "秩序", "沉浸", "时间感消失"],
     "recovery": "拼图期间心率维持在 71bpm 左右，压力指数持续下降"},
    {"label": "修旧家电", "category": "STRESS_CONTROL_REBUILD",
     "dimension_id": "dim:candidate_stress_control_rebuild",
     "dimension_name": "逆境下掌控感重建倾向",
     "timeline": "把客厅那台积灰的落地扇拆开，清灰、上油、重新接线，装回去后按下开关，风出来了",
     "app": None, "kind": "LIFE", "source": "SENSOR",
     "evidence_kw": ["修理", "可控", "修复", "成就感"],
     "recovery": "修好后心率回落至基线，情绪压力指数下降 38%"},
    {"label": "给家人备药", "category": "STRESS_LIFE_CULTIVATION_COPING",
     "dimension_id": "dim:candidate_stress_life_cultivation",
     "dimension_name": "逆境下照料生命式意义重建倾向",
     "timeline": "把家里的药箱从头整理一遍，清掉过期药，按人头分装好，贴上标签写明用法",
     "app": None, "kind": "LIFE", "source": "SENSOR",
     "evidence_kw": ["照料家人", "分类", "预案", "责任感"],
     "recovery": "整理期间心率稳定，睡前情绪压力指数较 3 小时前下降 33%"},
    {"label": "写五年现金流", "category": "STRESS_CONTROL_REBUILD",
     "dimension_id": "dim:candidate_stress_control_rebuild",
     "dimension_name": "逆境下掌控感重建倾向",
     "timeline": "打开表格，把未来五年的收入、月供、父母医疗预留款逐行推演了一遍，做成三张敏感性分析表",
     "app": "Excel", "kind": "WORK", "source": "APP",
     "evidence_kw": ["财务推演", "掌控感", "长期规划", "焦虑转化"],
     "recovery": "推演结束后心率 76bpm，情绪压力指数较峰值下降 44%"},
    {"label": "剪一条 Vlog", "category": "STRESS_NARRATIVE_REFRAME",
     "dimension_id": "dim:candidate_stress_narrative_reframe",
     "dimension_name": "逆境下叙事重构自愈倾向",
     "timeline": "把手机里这半年的碎片素材剪成一条三分钟短片，还给结尾配了一段旁白",
     "app": "剪辑软件", "kind": "HOBBY", "source": "APP",
     "evidence_kw": ["剪辑", "叙事", "重构", "自我叙述"],
     "recovery": "剪片期间心率平稳在 74bpm，压力指数回落"},
    {"label": "重读旧日记", "category": "STRESS_NARRATIVE_REFRAME",
     "dimension_id": "dim:candidate_stress_narrative_reframe",
     "dimension_name": "逆境下叙事重构自愈倾向",
     "timeline": "翻出三年前的日记本，从第一页读到最后，在末页补写了一段“其实那时候也熬过来了”",
     "app": None, "kind": "NOTE", "source": "SENSOR",
     "evidence_kw": ["日记", "回顾", "意义重述", "自我安慰"],
     "recovery": "读日记期间心率 72bpm，皮温回升 1.1℃"},
    {"label": "通宵打游戏", "category": "STRESS_IMMERSION_ESCAPE",
     "dimension_id": "dim:candidate_stress_immersion_escape",
     "dimension_name": "逆境下沉浸式逃离代偿倾向",
     "timeline": "戴上耳机连打了四个小时游戏，把该刷的副本刷完，期间没看手机",
     "app": "游戏客户端", "kind": "HOBBY", "source": "APP",
     "evidence_kw": ["游戏", "沉浸", "逃逸", "屏蔽现实"],
     "recovery": "游戏期间心率 80bpm，压力指数短期下降但入睡推迟"},
    {"label": "深夜骑行", "category": "STRESS_PHYSICAL_DISCHARGE",
     "dimension_id": "dim:candidate_stress_physical_discharge",
     "dimension_name": "逆境下高强度体能耗散倾向",
     "timeline": "一个人骑车绕湖两圈，共 22 公里，全程没有说话，只在最后一圈放慢了踏频",
     "app": "骑行 APP", "kind": "ACTIVITY", "source": "SENSOR",
     "evidence_kw": ["骑行", "独处", "体力消耗", "冷静"],
     "recovery": "骑行结束后心率回落至 86bpm，情绪压力指数下降 39%"},
    {"label": "修整老照片", "category": "STRESS_NOSTALGIC_SOOTHE",
     "dimension_id": "dim:candidate_stress_nostalgic_soothe",
     "dimension_name": "逆境下怀旧安抚倾向",
     "timeline": "把家里旧相册里受潮的照片一张张扫描进电脑，破损的地方用软件慢慢修补",
     "app": "修图软件", "kind": "HOBBY", "source": "APP",
     "evidence_kw": ["旧照片", "修复", "怀旧", "慢动作"],
     "recovery": "修图期间心率稳定在 73bpm，呼吸频率下降"},
    {"label": "深夜临帖", "category": "STRESS_RITUAL_CALM",
     "dimension_id": "dim:candidate_stress_ritual_calm",
     "dimension_name": "逆境下仪式化静心代偿倾向",
     "timeline": "铺开毛边纸，把一本字帖从第一页临到第十页，墨干了才停手",
     "app": None, "kind": "NOTE", "source": "SENSOR",
     "evidence_kw": ["临帖", "书法", "呼吸节律", "静心"],
     "recovery": "临帖结束时心率 69bpm，HRV 较最低点回升 15ms"},
]


# ---------------------------------------------------------------------------
# B 卷专属：隐性内耗与潜台词（白天表面表演 vs 深夜私密宣泄）
# ---------------------------------------------------------------------------
SUBTLE_MOTIFS: List[Dict[str, Any]] = [
    {"surface": "在客户电话里连着说了七遍“您放心，我们一定搞定”，挂断后嘴角立刻垮了下来",
     "undertone_channel": "微信", "undertone": "深夜给唯一的好友发消息：“我今天笑得脸都僵了，其实心里在骂人。”",
     "evidence_kw": ["情绪劳动", "强颜欢笑", "面具成本"], "vital": "通话结束后皮温下降 1.3℃，HRV 由 46ms 降到 28ms"},
    {"surface": "被同事当众甩锅，他/她微笑着说“是我考虑不周，我来改”，回到座位上把指甲掐进掌心",
     "undertone_channel": "备忘录", "undertone": "深夜在备忘录里写：“今天第八次替别人认错，我真的一点力气都没有了。”",
     "evidence_kw": ["表面顺从", "自我耗损", "隐忍"], "vital": "掐掌心时心率 96bpm，HRV 骤降至 21ms"},
    {"surface": "部门团建上被要求讲段子活跃气氛，他/她讲了三个笑话，全场都笑了",
     "undertone_channel": "微信", "undertone": "夜里给发小发语音：“我一句话都不想说了，你别回我，就让我躺着。”",
     "evidence_kw": ["社交耗竭", "表演型外向", "电量耗尽"], "vital": "团建结束后皮温下降 1.5℃，静息心率比晨起高 18bpm"},
    {"surface": "母亲打来电话，他/她说“我这边一切都好，工作顺利，你们别操心”，语气轻快",
     "undertone_channel": "朋友圈", "undertone": "挂断后把朋友圈一条条翻到去年，看完默默锁屏，什么都没发。",
     "evidence_kw": ["报喜不报忧", "孤独", "双面生活"], "vital": "通话 4 分 12 秒，挂断后心率由 74bpm 升至 92bpm"},
    {"surface": "被领导点名批评，他/她全程点头记录，还在会议纪要里补了一句“感谢指正”",
     "undertone_channel": "微信", "undertone": "深夜把这段对话逐字复述给好朋友，最后说：“我只是想有人知道我没错。”",
     "evidence_kw": ["委屈", "不被认可", "需要见证"], "vital": "复述时心率 98bpm，皮温下降 1.6℃"},
    {"surface": "同事问他/她最近怎么样，他/她笑着说“挺好的，就是有点忙”",
     "undertone_channel": "微信", "undertone": "夜里向朋友吐露：“我每天都想请一天假，但我不敢。”",
     "evidence_kw": ["表面平稳", "内里透支", "不敢停"], "vital": "白天心率波动不大，夜间 HRV 最低降至 20ms"},
    {"surface": "汇报被当场打断三次，他/她仍然把 PPT 讲完，最后说“谢谢大家的时间”",
     "undertone_channel": "备忘录", "undertone": "深夜写下：“他们根本不想听我说话，我准备了两周。”",
     "evidence_kw": ["被忽视", "努力被清零", "自尊受损"], "vital": "汇报后 20 分钟心率 94bpm，皮温下降 1.2℃"},
    {"surface": "{pronoun}在家族群里发了两个红包，配文“今年一切都好，大家放心”",
     "undertone_channel": "微信", "undertone": "同一晚给朋友发消息：“我妈问我存款的时候，我手心全是汗。”",
     "evidence_kw": ["家庭体面", "隐瞒", "羞耻感"], "vital": "发红包时心率 88bpm，夜间 HRV 下降 14ms"},
    {"surface": "客户骂了十分钟，他/她全程只说“是我们的问题，马上处理”",
     "undertone_channel": "微信", "undertone": "挂了电话把手机扣在桌上，给朋友发：“我现在特别想砸点东西。”",
     "evidence_kw": ["情绪劳动", "愤怒抑制", "躯体化"], "vital": "骂声结束后皮温下降 1.8℃，HRV 降至 19ms"},
    {"surface": "{pronoun}在会议上主动承担了本不属于自己的锅，散会时还被夸“有担当”",
     "undertone_channel": "备忘录", "undertone": "深夜写下：“有担当三个字，值一顿没人知道的眼泪。”",
     "evidence_kw": ["讨好型", "责任越界", "自我消耗"], "vital": "散会后心率 90bpm，深夜皮温下降 1.4℃"},
    {"surface": "{pronoun}把新买的西装穿上出门，同事都说精神，{pronoun}笑着说“谢谢”",
     "undertone_channel": "微信", "undertone": "晚上对朋友说：“穿得再精神，账户余额也不会好看起来。”",
     "evidence_kw": ["体面维持", "财务焦虑", "撕裂"], "vital": "白天的 HRV 基线整体下移 6ms，夜间未回升"},
    {"surface": "{pronoun}在朋友圈发了一张加班的照片，配文“热爱可抵岁月漫长”",
     "undertone_channel": "微信", "undertone": "发布三分钟后给闺蜜发：“我真的很想辞职，但房贷不允许。”",
     "evidence_kw": ["人设管理", "现实困境", "无人可说"], "vital": "发圈后心率 86bpm，皮温下降 1.1℃"},
    {"surface": "他/她整个白天都在照顾部门新人的情绪，午饭都分给别人吃",
     "undertone_channel": "微信", "undertone": "晚上一个人吃了泡面，给朋友发：“我好像从来没有被人这样照顾过。”",
     "evidence_kw": ["过度付出", "被忽视", "匮乏感"], "vital": "全天 HRV 缓慢下降，夜间最低 22ms"},
    {"surface": "客户临时改需求到第五版，{pronoun}回了一句“没问题，我今晚给您”",
     "undertone_channel": "备忘录", "undertone": "深夜写下：“我不是没问题，我是不敢有问题。”",
     "evidence_kw": ["不得不顺从", "自我压缩", "疲惫"], "vital": "当夜 HRV 最低 18ms，皮温较基线下降 2.1℃"},
    {"surface": "{pronoun}在电梯里遇到领导，笑着说了两分钟场面话，还在电梯口目送领导先走",
     "undertone_channel": "微信", "undertone": "回到工位给同事发：“每次电梯里那两分钟，我都觉得自己在演一部烂片。”",
     "evidence_kw": ["角色扮演", "自我疏离", "内耗"], "vital": "电梯后心率 92bpm，20 分钟后仍未回落至基线"},
    {"surface": "{pronoun}连着三天在跨部门协调会上主持控场，全程陪笑推进",
     "undertone_channel": "微信", "undertone": "散会后给大学室友发消息：“我笑了三个小时，现在脸都不想动。”",
     "evidence_kw": ["社交耗竭", "控场", "陪笑"], "vital": "会议结束后 40 分钟内 HRV 由 45ms 降至 22ms，皮温下降 1.4℃"},
    {"surface": "{pronoun}整整一周对外应酬，每天把客人送到楼下才松一口气",
     "undertone_channel": "微信", "undertone": "周五夜里给发小发消息：“我下周谁都不想见，谁都别约我。”",
     "evidence_kw": ["社交透支", "应酬", "独处需求"], "vital": "连续五天后 HRV 基线整体下移 8ms，夜间皮温持续偏低"},
    {"surface": "{pronoun}在朋友圈发了条工作动态，配文“继续努力”，同事纷纷点赞",
     "undertone_channel": "备忘录", "undertone": "发完之后反复点开看，五分钟后把这条动态删掉了。",
     "evidence_kw": ["自我审查", "不满足", "删除"], "vital": "反复点开期间心率 88bpm，皮温下降 1.2℃，HRV 降至 24ms"},
    {"surface": "{pronoun}交上去的工作日报里写着“一切顺利，无风险项”",
     "undertone_channel": "备忘录", "undertone": "写日报前对着清单划掉了 11 项没做完的事，最后一句只敢写“明天补上”。",
     "evidence_kw": ["完美主义", "隐瞒进度", "自我苛责"], "vital": "写日报期间心率 84bpm 持续 40 分钟，HRV 由 41ms 降至 25ms"},
    {"surface": "{pronoun}白天刚帮一位客户垫付了停车费，客户连声道谢",
     "undertone_channel": "微信", "undertone": "夜里给妻子发消息：“今天又垫了钱，我不想告诉你。”",
     "evidence_kw": ["金钱隐瞒", "边界失守", "羞耻"], "vital": "当晚 HRV 最低 21ms，皮温下降 1.7℃"},
    {"surface": "{pronoun}在家长会上被老师点名表扬，笑着一再感谢",
     "undertone_channel": "微信", "undertone": "回到家给姐姐发：“我连孩子作业都没时间看，我配吗？”",
     "evidence_kw": ["自我怀疑", "角色撕裂", "内疚"], "vital": "家长会后心率 90bpm，夜间皮温下降 1.3℃"},
    {"surface": "{pronoun}上午刚做完一场成功的公开分享，掌声持续了十几秒",
     "undertone_channel": "备忘录", "undertone": "散场后坐进车里很久没动，备忘录里写：“掌声停下来的那一秒最难受。”",
     "evidence_kw": ["成就性空虚", "落差", "自我怀疑"], "vital": "散场后心率骤降又反弹至 94bpm，皮温下降 1.0℃"},
    {"surface": "{pronoun}今天在群里被表扬了三次，回复都很得体",
     "undertone_channel": "微信", "undertone": "深夜却对方说：“我配不上这些夸奖，我只是不敢出错。”",
     "evidence_kw": ["冒充者综合征", "不敢出错", "高压"], "vital": "表扬后半段心率持续 85bpm 以上，HRV 未回升"},
    {"surface": "{pronoun}白天对下属的错误处理得温和克制，没有发火",
     "undertone_channel": "微信", "undertone": "夜里跟朋友说：“我压了一天的火，现在胸口一直发紧。”",
     "evidence_kw": ["愤怒抑制", "躯体紧张", "情绪劳动"], "vital": "夜间胸口发紧时心率 96bpm，皮温下降 1.5℃"},
    {"surface": "{pronoun}忍住了跟母亲顶嘴的冲动，笑着把话岔开",
     "undertone_channel": "备忘录", "undertone": "深夜写：“我其实很想当面说出来，我真的很累。”",
     "evidence_kw": ["代际压抑", "未说出口", "心累"], "vital": "当夜入睡潜伏期 78 分钟，HRV 最低 23ms"},
    {"surface": "{pronoun}白天把同事分享的零食一口一口吃完了，还夸好吃",
     "undertone_channel": "微信", "undertone": "晚上独自在车里坐了很久，给朋友发：“我今天一整天都在假装胃口很好。”",
     "evidence_kw": ["假装正常", "躯体反应", "孤独"], "vital": "晚饭后心率 92bpm，皮温下降 1.2℃"},
    {"surface": "{pronoun}在朋友圈给所有同事的新动态点了赞",
     "undertone_channel": "备忘录", "undertone": "点完后在备忘录里写：“我是什么时候开始，连讨厌都不敢了。”",
     "evidence_kw": ["讨好", "自我消失", "低电量"], "vital": "点赞后心率 86bpm，HRV 降至 26ms"},
    {"surface": "{pronoun}整个白天都在安慰刚失恋的同事，说了两个小时",
     "undertone_channel": "微信", "undertone": "回到家自己在玄关坐了很久，给闺蜜发：“其实我也想有人这样安慰我。”",
     "evidence_kw": ["情感供养", "未被照顾", "空耗"], "vital": "安慰结束后心率 78bpm，夜间 HRV 最低 24ms"},
    {"surface": "{pronoun}面试完对 HR 说“期待加入贵公司”，握手时笑得很标准",
     "undertone_channel": "微信", "undertone": "下楼后给朋友发：“如果这次又没过，我真的不知道还能撑多久。”",
     "evidence_kw": ["求职压力", "绝望感", "强撑"], "vital": "面试结束后心率 100bpm，皮温下降 1.6℃"},
    {"surface": "{pronoun}在家庭群里一一回复了长辈的消息，每条都带表情包",
     "undertone_channel": "备忘录", "undertone": "关掉群聊后写：“我连自己都快照顾不了了。”",
     "evidence_kw": ["家庭义务", "透支", "关闭群聊"], "vital": "关群后心率 88bpm，HRV 由 40ms 降至 25ms"},
    {"surface": "{pronoun}整个白天都在给团队打气，说“这个项目一定能成”",
     "undertone_channel": "微信", "undertone": "深夜却对妻子坦白：“其实我心里一点底都没有。”",
     "evidence_kw": ["被迫乐观", "双重身份", "内耗"], "vital": "夜里心率 90bpm，皮温下降 1.4℃"},
    {"surface": "{pronoun}在电梯里被陌生人夸了一句“看起来状态真好”，笑着道谢",
     "undertone_channel": "备忘录", "undertone": "回到办公室写：“他们不知道我昨晚在洗手间哭了多久。”",
     "evidence_kw": ["外表与内里断裂", "隐藏", "哀伤"], "vital": "当天 HRV 整体偏低 7ms，夜间皮温下降 1.9℃"},
    {"surface": "{pronoun}白天拒绝了同事的加班请求，理由说得体面又委婉",
     "undertone_channel": "微信", "undertone": "夜里反复回放拒绝的那几句话，给朋友发：“我是不是太自私了。”",
     "evidence_kw": ["边界内疚", "反刍", "自我质疑"], "vital": "反刍期间心率 92bpm，入睡潜伏期 65 分钟"},
    {"surface": "{pronoun}在电话里平静地听完母亲的抱怨，一句都没反驳",
     "undertone_channel": "备忘录", "undertone": "挂断后写：“我好像永远是那个被要求懂事的人。”",
     "evidence_kw": ["懂事负担", "被要求", "压抑"], "vital": "挂断后 HRV 由 44ms 降至 23ms，皮温下降 1.5℃"},
]


# ---------------------------------------------------------------------------
# 场景级职业适配：把“只有某个职业才说得通”的受挫素材锁定到具体职业，
# 其余素材保持域内通用，避免“地铁站值班站长被业主投诉物业”这类错配。
# ---------------------------------------------------------------------------
_SETBACK_OCC: Dict[str, List[str]] = {
    "物业费我们交着": ["物业服务项目经理"],
    "同商圈三家店就你的营业额垫底": ["连锁餐饮门店店长", "社区咖啡店店主"],
    "这道投诉已经记在你名下": ["民航乘务长"],
    "我妈背上起红疹了": ["养老机构护理主管", "社区医院全科医生"],
    "这次乘客纠纷的处理你全程被动": ["地铁站值班站长", "民航乘务长"],
    "这杯咖啡的味道完全不对": ["社区咖啡店店主"],
    "这个工序返工两次": ["建筑工地项目经理"],
    "这单又超时了": ["货运司机"],
    "电梯困人三十五分钟": ["电梯维保技师"],
    "你昨晚那条负荷曲线判断错了": ["国有电网运维调度员"],
    "爆仓了你才说预案不够": ["物流园区调度主管"],
    "那起邻里纠纷你调解了三次": ["基层派出所社区民警"],
    "你片区被通报了两处卫生死角": ["城市环卫片区班长"],
    "这批菜退货了一半": ["有机农场主理人"],
    "良率掉成这样": ["芯片封装工艺工程师", "半导体测试工程师"],
    "这批样衣尺寸全错了": ["服装厂版房主管"],
    "你班组的排产又插错了单": ["家具厂数控开料工"],
    "程式优化拖了三周": ["半导体测试工程师", "芯片封装工艺工程师"],
    "这份方案谁签的字": ["三甲医院麻醉科主治医师"],
    "你们是不是把药弄错了": ["三甲医院急诊科护士", "连锁药房执业药师"],
    "交接记录少了一项": ["三甲医院急诊科护士", "养老机构护理主管"],
    "预约排程全乱了": ["三甲医院放射科技师"],
    "排了三个小时你就说这几句话": ["社区医院全科医生", "口腔科执业医师", "乡镇卫生院公卫医师"],
    "你班平均分又是垫底": ["初中语文教师兼班主任", "公立小学英语教师", "初中化学教师"],
    "这个教案逻辑是断的": ["公立小学英语教师", "初中语文教师兼班主任", "初中化学教师", "小学体育教师"],
    "我孩子说你昨天当众凶他": ["初中语文教师兼班主任", "公立小学英语教师", "初中化学教师", "小学体育教师", "幼儿园大班主班老师"],
    "你负责的学生心理台账不全": ["高职院校辅导员"],
    "你带的选手市赛连名次都没进": ["中职学校汽修实训教师"],
    "孩子磕了一下你们都不知道": ["幼儿园大班主班老师"],
    "这批数据重复不出来": ["高校实验员"],
    "这条片子重剪第三遍了": ["纪录片剪辑师"],
    "这稿子问题太多": ["出版社图书编辑"],
    "你这篇报道的核心事实没核实清楚": ["地方融媒体中心记者"],
    "方案完全不是我要的感觉": ["自由插画师", "装修公司设计总监", "文旅项目策划"],
    "这组片子拍成这样": ["自由摄影师"],
    "嘉宾说下半场翻译跟不上": ["英语同声传译"],
    "连续两个月没开单": ["汽车零部件销售经理", "二手房产经纪人", "城市综合体招商主管"],
    "你们报价比对手高三成": ["汽车零部件销售经理"],
    "这个月你的带看转化是店里最低": ["二手房产经纪人"],
    "这批货损耗率这么高": ["生鲜超市采购主管"],
    "主力店签约又黄了": ["城市综合体招商主管"],
    "你的对公存款完成率全行倒数第一": ["城商行对公客户经理"],
    "这案子客户要换人": ["小型律所执业律师"],
    "季末揽储任务你差一半": ["国有银行网点柜员"],
    "你这份审查意见前后矛盾": ["银行总行风险审查岗"],
    "这份材料连基本数据都对不上": ["区级机关综合科科员"],
    "这份笔录关键处漏记了": ["人民法院书记员"],
    "这篇稿子被上面点名批评": ["国企宣传干事"],
    "那个群众投诉又回到我们头上了": ["基层派出所社区民警"],
    "这份方案连最基本的容灾与回滚都没写": ["互联网后端架构师", "互联网大厂产品经理", "互联网数据分析师",
                                              "游戏公司数值策划", "软件外包交付项目经理", "跨境电商独立站卖家",
                                              "国营施工图结构设计师", "档案数字化项目经理"],
    "你的项目又延期了": ["互联网后端架构师", "互联网大厂产品经理", "软件外包交付项目经理",
                          "游戏公司数值策划", "档案数字化项目经理"],
    "你们交付的东西根本不能用": ["软件外包交付项目经理", "互联网后端架构师", "档案数字化项目经理",
                                  "国营施工图结构设计师"],
    "这个线上事故你负全责": ["互联网后端架构师", "软件外包交付项目经理", "互联网数据分析师"],
    "会上把你数据里的问题逐条念了出来": ["互联网数据分析师", "互联网大厂产品经理", "电商平台运营主管"],
    "公司要优化，你的岗位在下季度名单里": ["互联网后端架构师", "互联网大厂产品经理", "电商平台运营主管",
                                            "互联网数据分析师", "游戏公司数值策划", "软件外包交付项目经理",
                                            "跨境电商独立站卖家", "档案数字化项目经理", "国营施工图结构设计师"],
    "家属连流程都没被告知清楚": ["殡葬礼仪服务师"],
    "你的续课率是全店最低": ["健身工作室私教"],
    "这处隐患你排查了一周还在": ["轨道交通信号检修工"],
    "这台设备停了三天还没修好": ["医疗器械售后工程师"],
    "你班组这个月的不良率又超了": ["五金厂车间班组长"],
    "这例手术方案你怎么定的": ["宠物医院执业兽医师"],
    "区域督导": ["连锁餐饮门店店长"],
}

for _entry in CAREER_SETBACKS:
    _quote = _entry["quote"]
    for _key, _occs in _SETBACK_OCC.items():
        if _key in _quote:
            _entry["occ"] = list(_occs)
            break

# 质量自检：素材场景必须能被至少一个职业承接
MANUAL_REVIEW_SETBACKS = [e for e in CAREER_SETBACKS
                          if not e.get("occ") and e["domain"] in {"FINANCE", "SERVICE"}]


# ---------------------------------------------------------------------------
# 危机素材的题型归属：含长辈健康/医疗字样的素材只在 C 卷（长辈危机卷）使用，
# A/B 卷只保留情感、家庭（非长辈健康）、财务与职场类危机。
# ---------------------------------------------------------------------------
ELDER_HEALTH_KW = ("住院", "手术", "检查单", "复查", "老毛病", "病理", "化验", "陪护", "护工")


def elder_health_motif(motif: Dict[str, Any]) -> bool:
    blob = motif["text"] + " ".join(motif.get("kw", []))
    return any(k in blob for k in ELDER_HEALTH_KW)
