"""生活流素材池 · C/D 卷：长辈突发危机、借贷与疑似诈骗、平静日常与偶发体征波动。

约定：
- C 卷素材严禁给出确诊结论，只允许“未明说的担忧、待检查、待复查、家里不肯细说”；
- 诈骗素材必须给出可核查的红旗特征（非官方域名、索要验证码、要求转账到“安全账户”等）；
- D 卷素材全部为良性日常，禁止任何冲突类事件，供答卷练习“克制不衍生”。
"""

from __future__ import annotations

from typing import Any, Dict, List

# ---------------------------------------------------------------------------
# C 卷：长辈突发危机（28 条）；channel 决定落入 MIC / APP 通道
# ---------------------------------------------------------------------------
FAMILY_CRISIS_C: List[Dict[str, Any]] = [
    {"channel": "电话", "who": "舅舅", "kw": ["长辈健康", "语气异常", "不明说"],
     "text": "舅舅打来电话，语气压得很低：“你妈今天去医院拿片子了，家里人都瞒着你，我觉得该让你知道。”"},
    {"channel": "电话", "who": "姐姐", "kw": ["检查未定论", "让回家", "悬置"],
     "text": "姐姐打来电话：“爸的检查结果不太好看，医生说还要再做一次，你先别跟妈说是我告诉你的。”"},
    {"channel": "微信", "who": "母亲", "kw": ["隐瞒", "轻描淡写", "不安"],
     "text": "母亲发来消息：“家里都好，你爸就是老毛病犯了，吃点药就没事。你好好上班。”后面跟着一个微笑的表情。"},
    {"channel": "电话", "who": "姑姑", "kw": ["长辈健康", "不配合就医", "无能为力"],
     "text": "姑姑来电：“你妈最近总说胸口闷，也不肯去医院，你有空劝劝她。”"},
    {"channel": "微信", "who": "父亲", "kw": ["住院", "无人陪护", "愧疚"],
     "text": "父亲发来一张病房照片，配了一句：“就是住两天观察，你妈不让告诉你，我偷偷说的。”"},
    {"channel": "电话", "who": "邻居阿姨", "kw": ["突发", "邻里援手", "心慌"],
     "text": "老家邻居打来电话：“上午看到救护车停在你家门口，你妈被抬上车了，你现在赶紧问问。”"},
    {"channel": "电话", "who": "表哥", "kw": ["借钱就医", "家庭资金", "两难"],
     "text": "表哥打来电话：“叔住院要先交押金，家里凑不太齐，你这边能不能先垫一部分？”"},
    {"channel": "微信", "who": "母亲", "kw": ["住院费用", "不肯麻烦", "心酸"],
     "text": "母亲发来消息：“住院的事你别管，我们自己能行，你钱留着自己用。”"},
    {"channel": "电话", "who": "弟弟", "kw": ["弟弟撒谎", "家庭秘密", "被排除"],
     "text": "弟弟打来电话，声音有点慌：“哥/姐，妈最近瘦了很多，她不让我说，你回来看看吧。”"},
    {"channel": "电话", "who": "县医院医生", "kw": ["需要家属", "进一步检查", "未知"],
     "text": "陌生号码来电，自称县医院医生：“您母亲的检查结果需要家属来一趟当面沟通，电话里不方便说。”"},
    {"channel": "微信", "who": "家族群", "kw": ["家庭群消息", "众筹倾向", "压力"],
     "text": "家族群里有人转发了一条筹款链接，@了本人：“先看看这个流程，后面也许用得上。”"},
    {"channel": "电话", "who": "父亲", "kw": ["父亲病倒", "强撑", "责任感"],
     "text": "父亲打来电话，声音很轻：“我这两天头晕得厉害，没敢跟你妈说，你那边忙不忙？”"},
    {"channel": "视频", "who": "母亲", "kw": ["视频里的异样", "消瘦", "不敢问"],
     "text": "视频通话里母亲比上次瘦了一圈，说话时总要停下来喘，她解释说是“最近没睡好”。"},
    {"channel": "微信", "who": "姑姑", "kw": ["费用", "家庭协商", "责任分配"],
     "text": "姑姑在微信上说：“你爸妈这次的事，费用几兄妹是不是要坐下来商量一下？你是最有出息的。”"},
    {"channel": "电话", "who": "老家村医", "kw": ["基层医疗", "转诊建议", "紧迫"],
     "text": "村医打来电话：“您父亲的血压这两天一直压不下来，我建议尽快转去市里看看，你们家属定一下。”"},
    {"channel": "微信", "who": "母亲", "kw": ["求助", "第一次示弱", "心碎"],
     "text": "母亲发来语音，声音发颤：“你爸今天又摔了一下，我一个人扶不起来……”"},
    {"channel": "电话", "who": "岳父母", "kw": ["姻亲健康", "家庭义务", "进退"],
     "text": "伴侣的父母打来电话：“你爸体检有点问题，想让你陪着去大医院看看，你看什么时候方便。”"},
    {"channel": "微信", "who": "堂姐", "kw": ["返乡", "工作冲突", "两难"],
     "text": "堂姐发来消息：“这周末家里要商量老人的事，你要是回得来就回来一趟，回不来我们也能理解。”"},
    {"channel": "电话", "who": "母亲", "kw": ["病情拖延", "省钱", "心疼"],
     "text": "母亲在电话里说：“医生说可以住院也可以先吃药，我选了吃药，能省不少。”"},
    {"channel": "微信", "who": "社区网格员", "kw": ["独居老人", "上门走访", "担忧"],
     "text": "老家社区网格员发来消息：“今天上门走访，敲了二十分钟门没人应，后来你爸从里屋出来了，最近你多关注一下。”"},
    {"channel": "电话", "who": "舅舅", "kw": ["家族气压", "被要求表态", "压力"],
     "text": "舅舅打来电话：“家里现在都等你一句话，你妈这病到底怎么治，你拿个主意。”"},
    {"channel": "微信", "who": "父亲", "kw": ["沉默的父亲", "转账", "心酸"],
     "text": "父亲发来一条转账请求，备注写着“买点药”，金额很小，是本人工作十年来第一次收到他的转账请求。"},
    {"channel": "电话", "who": "妹妹", "kw": ["妹妹求助", "家庭负担", "无退路"],
     "text": "妹妹打来电话，哭着说：“妈不让我告诉你，可我一个人真的扛不住了。”"},
    {"channel": "微信", "who": "母亲", "kw": ["拒绝就医", "代际固执", "焦虑"],
     "text": "母亲在微信里回绝：“别给我约号了，人老了哪有不难受的，你们别拿我当病人。”"},
    {"channel": "电话", "who": "医院导医", "kw": ["预约冲突", "必须到场", "分身乏术"],
     "text": "医院来电确认预约：“您帮家属约的检查下周二上午，需要有人全程陪同，请安排时间。”"},
    {"channel": "微信群", "who": "高中同学", "kw": ["同龄人对照", "父母健康", "焦虑放大"],
     "text": "同学群里有人发了条消息：“刚送我爸做支架，人到中年真是扛不住。”下面跟着一串感叹。"},
    {"channel": "电话", "who": "母亲的主治医生", "kw": ["需进一步检查", "不确诊", "等待"],
     "text": "医生打来电话：“目前还不能下结论，建议完善几项检查后再看，家属先不要过度紧张。”"},
    {"channel": "微信", "who": "二姨", "kw": ["家族意见", "被比较", "委屈"],
     "text": "二姨发来消息：“你哥他们都在外地，家里就靠你了，你妈最疼的就是你。”"},
]

# ---------------------------------------------------------------------------
# C 卷：疑似诈骗信息（20 条）：channel + 内容 + 红旗特征 + 合规动作
# ---------------------------------------------------------------------------
FRAUD_C: List[Dict[str, Any]] = [
    {"channel": "短信", "sender": "【社保局】",
     "text": "【社保局】您的养老金资格认证已过期，请于 24 小时内点击 t.cn/Ax7k2 完成人脸认证，逾期将暂停发放。",
     "red_flags": ["非官方短链域名", "以停发待遇制造紧迫感", "要求点击链接做人脸认证"],
     "safe_actions": ["不点击链接", "通过国家社会保险公共服务平台或 12333 官方渠道核实", "如已点击立即修改相关信息并保留截图"]},
    {"channel": "短信", "sender": "【12381 反诈预警】仿冒前缀",
     "text": "【12381 反诈预警】您名下银行卡涉嫌异地案件，请立即联系办案民警核对资金，电话 021-6xxxxxxx。",
     "red_flags": ["仿冒官方前缀", "以涉案恐吓", "引导拨打非官方号码"],
     "safe_actions": ["不拨打短信中的号码", "直接拨打 110 或到就近派出所核实", "不提供银行卡号与验证码"]},
    {"channel": "短信", "sender": "【快递】",
     "text": "【快递】您的包裹因地址异常被退回，请点击 http://kd-yto.xyz 补填地址，逾期将自动销毁。",
     "red_flags": ["仿冒快递品牌的山寨域名", "以销毁包裹施压", "索要个人信息"],
     "safe_actions": ["不点击链接", "在购物 APP 内直接查看物流", "向平台官方客服核实"]},
    {"channel": "微信", "sender": "陌生好友「医院财务处」",
     "text": "您好，您母亲的住院押金尚差 8000 元，请转到下方对公账户，户名 ×××，稍后补开发票。",
     "red_flags": ["陌生账号自称医院财务", "要求转账到个人/不明对公账户", "绕过医院正式缴费渠道"],
     "safe_actions": ["不使用该账号转账", "回到医院官方窗口或公众号缴费", "电话向病区护士站核实"]},
    {"channel": "电话", "sender": "自称「医保局工作人员」",
     "text": "您的医保卡涉嫌违规使用，需要配合资金清查，请下载指定 APP 并把资金转入安全账户。",
     "red_flags": ["冒充医保部门", "要求下载不明 APP", "提及“安全账户”"],
     "safe_actions": ["直接挂断", "拨打 12393/12333 官方热线核实", "绝不下载任何屏幕共享类 APP"]},
    {"channel": "电话", "sender": "自称「公安经侦」",
     "text": "您涉嫌一起洗钱案，现在需要您配合做资金清查，全程不能告诉任何人，包括家人。",
     "red_flags": ["冒充公检法", "要求保密隔离", "诱导资金转移"],
     "safe_actions": ["立即挂断", "拨打 110 或 96110 核实", "第一时间告知家人"]},
    {"channel": "微信", "sender": "陌生好友「××银行客服」",
     "text": "您好，我是银行客服，检测到您的账户存在风险，请提供短信验证码协助我们冻结。",
     "red_flags": ["索要验证码", "冒充银行", "以风控名义套取信息"],
     "safe_actions": ["绝不提供验证码", "拨打银行官方客服电话核实", "如已提供立即挂失并报警"]},
    {"channel": "短信", "sender": "【税务局】",
     "text": "【税务局】您有一笔个税退税待领取，请点击链接填写银行卡号与密码以便打款。",
     "red_flags": ["索要银行卡密码（绝无此流程）", "仿冒税务部门", "以退税为诱饵"],
     "safe_actions": ["不点击链接", "通过个人所得税官方 APP 查询退税", "向 12366 核实"]},
    {"channel": "微信", "sender": "老家亲戚转发",
     "text": "转发：【内部名额】某平台养老理财，年化 24%，国家扶持，本息保障，只剩最后两小时。",
     "red_flags": ["超高收益承诺", "饥饿营销", "伪造国家背书"],
     "safe_actions": ["不参与、不转账", "提醒长辈该类项目不合法定资质", "通过国家金融监督管理总局官网核查机构资质"]},
    {"channel": "微信", "sender": "陌生好友「×校长」",
     "text": "我是你孩子学校的新任班主任，孩子今晚要交资料费 480 元，请扫码支付到我个人收款码。",
     "red_flags": ["冒充教师", "要求转到个人收款码", "以孩子在校事务施压"],
     "safe_actions": ["不在微信私聊里付款", "通过学校官方渠道核实", "直接联系孩子或班主任原号码确认"]},
    {"channel": "短信", "sender": "【ETC】",
     "text": "【ETC】您的 ETC 认证已失效，请点击 t.cn/Ex9d 重新认证，否则将影响高速通行。",
     "red_flags": ["仿冒 ETC 服务方", "短链域名", "以通行受限施压"],
     "safe_actions": ["不点击链接", "在发行方官方 APP 内查看", "拨打官方客服核实"]},
    {"channel": "电话", "sender": "自称「征信修复」机构",
     "text": "您有一条不良记录可以花钱修复，只要先付定金 2000 元，我们内部有人。",
     "red_flags": ["声称可修改征信", "先收费后办事", "所谓“内部关系”"],
     "safe_actions": ["拒绝转账", "知晓征信异议只能通过正规渠道提出", "向人民银行征信中心咨询"]},
    {"channel": "微信", "sender": "陌生好友「快递理赔专员」",
     "text": "您的快递丢失，我这边可以三倍理赔，请先加我微信并按指引操作退款。",
     "red_flags": ["主动理赔", "要求脱离平台私下操作", "后续多要求共享屏幕"],
     "safe_actions": ["在购物平台内申请理赔", "不共享屏幕", "不提供验证码与银行卡照片"]},
    {"channel": "短信", "sender": "【中国移动】仿冒",
     "text": "【中国移动】您的积分即将清零，请点击 wap.yd-jf.top 兑换现金。",
     "red_flags": ["山寨域名", "以清零制造紧迫感", "诱导填写个人信息"],
     "safe_actions": ["不点击链接", "在运营商官方 APP 内查看积分", "向官方客服核实"]},
    {"channel": "微信", "sender": "相亲对象",
     "text": "我这边有个稳赚的短线投资项目，你把钱转到我账户，我帮你操作，赚了算你的。",
     "red_flags": ["杀猪盘典型手法", "要求转入私人账户", "承诺稳赚"],
     "safe_actions": ["不转账", "终止投资类金钱往来", "保留聊天记录并向 96110 举报"]},
    {"channel": "电话", "sender": "自称「单位人事」",
     "text": "您有一笔补贴需要确认收款，请打开链接填写身份证号、银行卡号与验证码。",
     "red_flags": ["索要验证码", "以补贴为诱饵", "非官方通知渠道"],
     "safe_actions": ["挂断并向单位人事部门直接核实", "不提供任何验证码", "必要时报警"]},
    {"channel": "短信", "sender": "【交警】",
     "text": "【交警】您的车辆有一条违章未处理，请点击链接下载 APP 查看并缴纳罚款。",
     "red_flags": ["仿冒交管部门", "要求下载 APP", "非官方缴费渠道"],
     "safe_actions": ["不点击链接", "在交管 12123 官方 APP 查询", "向当地交警部门核实"]},
    {"channel": "微信", "sender": "老家邻居转发",
     "text": "邻居转发：有个微信群里说加客服就能领农村老人补贴，只要交 200 元手续费。",
     "red_flags": ["先收费后补贴", "针对老年人话术", "无任何官方出处"],
     "safe_actions": ["不交任何“手续费”", "向村委会或民政部门核实", "提醒长辈此类补贴不存在前置收费"]},
    {"channel": "电话", "sender": "自称「银保监」",
     "text": "您的保单有异常，可以提供工号，我们把钱退到您新的账户。",
     "red_flags": ["仿冒监管机构", "要求更换收款账户", "以退钱为诱饵"],
     "safe_actions": ["挂断并回拨保单上的官方电话", "不提供账户信息", "向监管机构官方渠道举报"]},
    {"channel": "短信", "sender": "【银行】仿冒",
     "text": "【银行】您的账户异常登录，请点击 t.cn/Bk31 冻结账户，超时后果自负。",
     "red_flags": ["以账户异常制造恐慌", "短链跳转钓鱼页", "索要密码与验证码"],
     "safe_actions": ["直接登录官方 APP 处理", "不点击链接", "如担心立即致电银行官方客服"]},
]

# ---------------------------------------------------------------------------
# C 卷：财务紧张切片（16 条，占位符由生成器按人设填充）
# ---------------------------------------------------------------------------
FINANCE_SLICES: List[Dict[str, Any]] = [
    {"text": "打开银行 APP 反复核算：房贷每月 {mortgage}，本月可支配结余只剩 {balance} 元，工资还要 {days} 天才到账。",
     "kw": ["资金紧张", "月供压力", "可支配结余告急"]},
    {"text": "把三张信用卡的账单日和还款额逐一抄在便签上，摆在桌角。",
     "kw": ["多卡还款", "现金流管理", "焦虑外化"]},
    {"text": "给老家转了一笔钱，转完后账户余额页面停留了很久没有退出。",
     "kw": ["赡养支出", "余额不忍看", "责任感"]},
    {"text": "在记账 APP 里把今天所有支出补录完，发现自己这个月已经超支 {over} 元。",
     "kw": ["超支", "记账", "失控感"]},
    {"text": "在电商平台把购物车里放了很久的东西一件件删掉，最后只留下了一包洗衣液。",
     "kw": ["消费降级", "克制", "无奈"]},
    {"text": "打开医院缴费小程序，反复查看了住院押金金额与报销比例，又退出来。",
     "kw": ["医疗支出预期", "报销比例", "不敢确认"]},
    {"text": "把手机银行里的理财赎回界面打开又关掉三次，最终没有赎回。",
     "kw": ["流动性焦虑", "进退两难"]},
    {"text": "算了一笔账：孩子下学期学费 {tuition}，父母体检预留 {checkup}，这两笔正好等于本月全部结余。",
     "kw": ["双重支出", "家庭账本", "无处腾挪"]},
    {"text": "同事聚餐时看到人均 {meal} 的账单，借着接电话提前离场，回家煮了碗面。",
     "kw": ["社交性支出压缩", "面子成本", "心酸"]},
    {"text": "把花呗和借呗的额度页面反复打开，最后还是没有点下借钱的按钮。",
     "kw": ["借贷边缘", "克制", "资金缺口"]},
    {"text": "在二手平台把闲置相机挂了上去，定价比买入时低了一半，备注写着“急出”。",
     "kw": ["变卖资产", "应急", "心理成本"]},
    {"text": "给孩子的兴趣班老师发消息问能不能缓交一个月学费，编辑了三次才点发送。",
     "kw": ["缓交请求", "尊严成本", "为人父母"]},
    {"text": "在手机银行里把房贷还款日往前调了一天，只为让工资到账与扣款顺序更安全。",
     "kw": ["现金流精细管理", "应激式优化"]},
    {"text": "打开家庭共享账本，看到今天又记了一笔医药费，看完什么也没说，退出了页面。",
     "kw": ["共同压力", "沉默共担"]},
    {"text": "把去年同期的账单翻出来做对比，发现月支出比去年涨了近 {rise} 成。",
     "kw": ["支出上涨", "对照焦虑"]},
    {"text": "深夜在搜索栏里输入“中年失业怎么办”，看完三条回答后清空了浏览记录。",
     "kw": ["失业恐惧", "隐蔽搜索", "不安全感"]},
]

# ---------------------------------------------------------------------------
# D 卷：平静日常切片（40 条，按 slot 分类，全部良性、无冲突）
# ---------------------------------------------------------------------------
CALM_DAY_SLICES: List[Dict[str, Any]] = [
    # ---- MORNING ----
    {"slot": "MORNING", "source": "SENSOR", "kind": "SLEEP", "app": None,
     "text": "自然醒，起床心率 62bpm，主诉“睡得不错”", "kw": ["自然醒", "睡眠充足"]},
    {"slot": "MORNING", "source": "APP", "kind": "LIFE", "app": "外卖 APP",
     "text": "下楼买了豆浆油条，顺路把门口的快递捎回来", "kw": ["日常采购", "慢节奏"]},
    {"slot": "MORNING", "source": "SENSOR", "kind": "LIFE", "app": None,
     "text": "扫了半小时地，把阳台的花浇了一遍", "kw": ["家务", "低强度活动"]},
    {"slot": "MORNING", "source": "APP", "kind": "ENTERTAINMENT", "app": "播客",
     "text": "边做早饭边听了一期播客，讲到一半就去忙别的了", "kw": ["背景音", "放松"]},
    {"slot": "MORNING", "source": "SENSOR", "kind": "ACTIVITY", "app": None,
     "text": "去楼下公园走了四十分钟，步数 4200", "kw": ["散步", "日常运动"]},
    {"slot": "MORNING", "source": "APP", "kind": "LIFE", "app": "买菜 APP",
     "text": "下单了下周的菜，顺手把常用清单又更新了一遍", "kw": ["备菜", "规律"]},
    {"slot": "MORNING", "source": "SENSOR", "kind": "SLEEP", "app": None,
     "text": "赖床二十分钟，翻了个身才起来，起床心率 68bpm", "kw": ["赖床", "放松"]},
    {"slot": "MORNING", "source": "APP", "kind": "CHAT", "app": "微信",
     "text": "在家庭群里回了句“周末回去吃饭”，又发了个笑脸", "kw": ["家常", "轻松"]},
    # ---- NOON ----
    {"slot": "NOON", "source": "APP", "kind": "LIFE", "app": "外卖 APP",
     "text": "中午点了份常吃的盖饭，吃得很干净", "kw": ["规律饮食"]},
    {"slot": "NOON", "source": "SENSOR", "kind": "ACTIVITY", "app": None,
     "text": "午饭后在小区里溜达了一圈，遇到邻居聊了两句天气", "kw": ["散步", "闲聊"]},
    {"slot": "NOON", "source": "APP", "kind": "ENTERTAINMENT", "app": "视频网站",
     "text": "看了半集综艺，笑点一般，当成背景音", "kw": ["休闲", "背景音"]},
    {"slot": "NOON", "source": "SENSOR", "kind": "SLEEP", "app": None,
     "text": "午睡三十五分钟，醒来有点懵，喝了杯水", "kw": ["午睡", "短暂"]},
    {"slot": "NOON", "source": "APP", "kind": "LIFE", "app": "购物 APP",
     "text": "把上周买的收纳盒退了货，理由选了“尺寸不合适”", "kw": ["退货", "日常事务"]},
    {"slot": "NOON", "source": "SENSOR", "kind": "LIFE", "app": None,
     "text": "把厨房台面擦了一遍，顺手把调料瓶按高矮排好", "kw": ["家务", "秩序"]},
    # ---- AFTERNOON ----
    {"slot": "AFTERNOON", "source": "SENSOR", "kind": "ACTIVITY", "app": None,
     "text": "在小区篮球场投了半小时篮，出了点汗", "kw": ["轻度运动", "休闲"]},
    {"slot": "AFTERNOON", "source": "APP", "kind": "READING", "app": "阅读 APP",
     "text": "看了二十几页闲书，做了两处划线，没有写笔记", "kw": ["阅读", "闲适"]},
    {"slot": "AFTERNOON", "source": "SENSOR", "kind": "LIFE", "app": None,
     "text": "把冬天的衣服收进真空袋，忙完后在阳台上晒了会儿太阳", "kw": ["换季整理", "晒太阳"]},
    {"slot": "AFTERNOON", "source": "APP", "kind": "HOBBY", "app": "手冲咖啡",
     "text": "手冲了一杯咖啡，按流程做完，坐着慢慢喝完", "kw": ["手冲", "慢生活"]},
    {"slot": "AFTERNOON", "source": "SENSOR", "kind": "HOBBY", "app": None,
     "text": "给阳台的多肉浇了水，把两片枯叶掐掉", "kw": ["养花", "照料"]},
    {"slot": "AFTERNOON", "source": "APP", "kind": "ENTERTAINMENT", "app": "游戏",
     "text": "打了两局游戏，赢一局输一局，没上头", "kw": ["游戏", "情绪平稳"]},
    {"slot": "AFTERNOON", "source": "SENSOR", "kind": "LIFE", "app": None,
     "text": "去楼下取了快递，顺便把楼道的纸箱折好放在回收点", "kw": ["日常琐事", "邻里"]},
    {"slot": "AFTERNOON", "source": "APP", "kind": "LIFE", "app": "出行 APP",
     "text": "查了下周末周边徒步的路线，收藏了两个帖子", "kw": ["计划", "期待感"]},
    {"slot": "AFTERNOON", "source": "SENSOR", "kind": "ACTIVITY", "app": None,
     "text": "陪孩子在小广场玩了四十分钟滑板车，全程站在旁边看着笑", "kw": ["亲子", "陪伴"], "requires_child": True},
    {"slot": "AFTERNOON", "source": "APP", "kind": "LIFE", "app": "家政 APP",
     "text": "预约了下周的深度保洁，顺手把时间改到周三下午", "kw": ["预约", "规划"]},
    # ---- EVENING ----
    {"slot": "EVENING", "source": "APP", "kind": "LIFE", "app": "买菜 APP",
     "text": "做了两个菜一个汤，吃完把碗筷都洗了", "kw": ["做饭", "规律"]},
    {"slot": "EVENING", "source": "SENSOR", "kind": "ACTIVITY", "app": None,
     "text": "沿着小区外圈快走了三圈，用时四十分钟", "kw": ["快走", "运动"]},
    {"slot": "EVENING", "source": "APP", "kind": "ENTERTAINMENT", "app": "视频网站",
     "text": "看了半场足球比赛，主队进了两个球，坐在沙发上拍了一下大腿", "kw": ["球赛", "兴奋但正常"]},
    {"slot": "EVENING", "source": "APP", "kind": "CHAT", "app": "微信",
     "text": "和老同学聊了几句近况，聊完互道“有空聚聚”", "kw": ["闲聊", "社交"]},
    {"slot": "EVENING", "source": "SENSOR", "kind": "LIFE", "app": None,
     "text": "把书房的书按类别重新排了一遍，整理出一摞准备捐掉", "kw": ["整理", "断舍离"]},
    {"slot": "EVENING", "source": "APP", "kind": "READING", "app": "阅读 APP",
     "text": "靠在沙发上看了会儿小说，看到一半困了就合上了书", "kw": ["阅读", "放松"]},
    {"slot": "EVENING", "source": "SENSOR", "kind": "HOBBY", "app": None,
     "text": "弹了四十分钟吉他，只练了一首老歌的和弦", "kw": ["乐器", "放松"]},
    {"slot": "EVENING", "source": "APP", "kind": "ENTERTAINMENT", "app": "音乐 APP",
     "text": "把播放器里的老歌单从头听了半张，跟着哼了几句", "kw": ["音乐", "怀旧但轻松"]},
    {"slot": "EVENING", "source": "SENSOR", "kind": "ACTIVITY", "app": None,
     "text": "陪家里的小狗在楼下遛了三十分钟，它跑得很欢", "kw": ["遛狗", "陪伴"]},
    {"slot": "EVENING", "source": "APP", "kind": "LIFE", "app": "购物 APP",
     "text": "在购物车里删掉了一件加购很久的东西，觉得没必要", "kw": ["理性消费"]},
    # ---- NIGHT ----
    {"slot": "NIGHT", "source": "SENSOR", "kind": "SLEEP", "app": None,
     "text": "洗漱后上床，2 分钟内入睡，夜间无异常报警", "kw": ["入睡顺利", "睡眠平稳"]},
    {"slot": "NIGHT", "source": "SENSOR", "kind": "SLEEP", "app": None,
     "text": "睡前把闹钟定在七点，放下手机就睡了", "kw": ["作息规律"]},
    {"slot": "NIGHT", "source": "APP", "kind": "READING", "app": "阅读 APP",
     "text": "睡前看了十页书，困了就关灯", "kw": ["睡前阅读"]},
    {"slot": "NIGHT", "source": "SENSOR", "kind": "SLEEP", "app": None,
     "text": "放下手机就睡着了，夜间心率最低 54bpm，无异常报警", "kw": ["入睡顺利", "正常"]},
    {"slot": "NIGHT", "source": "APP", "kind": "HOBBY", "app": "手账",
     "text": "写了两行今天的手账，贴了一张落叶标本的贴纸", "kw": ["手账", "记录"]},
    {"slot": "NIGHT", "source": "SENSOR", "kind": "SLEEP", "app": None,
     "text": "睡前把明天要穿的衣服叠好放在椅子上，关灯睡觉", "kw": ["准备", "踏实"]},
]

# ---------------------------------------------------------------------------
# D 卷：偶发短暂体征波动（20 条，全部有良性解释；trigger_* 为该波动之前真实发生的诱因切片）
# ---------------------------------------------------------------------------
BENIGN_VITALS_D: List[Dict[str, Any]] = [
    {"slot_pref": "DAWN", "delta": 18, "context": "清晨快速眼动期做梦醒来",
     "trigger_source": "SENSOR", "trigger_kind": "SLEEP", "trigger_app": None,
     "trigger_text": "夜里做了个梦醒了一次，翻了个身又睡回去",
     "mechanism": "清晨 REM 睡眠期交感神经自然活跃，心率短暂上升属正常生理现象",
     "kw": ["REM 睡眠", "生理性上升", "正常波动"]},
    {"slot_pref": "MORNING", "delta": 22, "context": "连续爬了六层楼到会议室",
     "trigger_source": "SENSOR", "trigger_kind": "ACTIVITY", "trigger_app": None,
     "trigger_text": "楼里电梯检修，从一楼连着爬了六层上来",
     "mechanism": "短时中等强度体力活动引起的生理性心率上升",
     "kw": ["体力活动", "生理性", "短时"]},
    {"slot_pref": "MIDDAY", "delta": 20, "context": "午后两杯美式咖啡后",
     "trigger_source": "APP", "trigger_kind": "LIFE", "trigger_app": "外卖 APP",
     "trigger_text": "点了两杯美式，坐在阳台上慢慢喝完",
     "mechanism": "咖啡因摄入引起的交感神经兴奋与心率短暂升高",
     "kw": ["咖啡因", "交感兴奋", "良性"]},
    {"slot_pref": "ANY", "delta": 24, "context": "蹲下系鞋带后快速起立",
     "trigger_source": "SENSOR", "trigger_kind": "LIFE", "trigger_app": None,
     "trigger_text": "蹲下系鞋带后快速起立，顺手把鞋柜上的鞋摆正",
     "mechanism": "体位改变引起的短暂心率波动，属正常体位反应",
     "kw": ["体位变化", "短暂波动", "正常反应"]},
    {"slot_pref": "EVENING", "delta": 26, "context": "看球赛主队进球瞬间",
     "trigger_source": "APP", "trigger_kind": "ENTERTAINMENT", "trigger_app": "视频网站",
     "trigger_text": "看球赛，主队进球时从沙发上坐直了身子",
     "mechanism": "情绪兴奋引起的短暂心率上升，属正常情绪生理反应",
     "kw": ["情绪兴奋", "瞬时", "无不适"]},
    {"slot_pref": "MIDDAY", "delta": 19, "context": "在商场里被突然的促销广播吓了一跳",
     "trigger_source": "APP", "trigger_kind": "LIFE", "trigger_app": "购物 APP",
     "trigger_text": "在商场一层逛街时，被突然响起的促销广播吓了一跳",
     "mechanism": "惊吓反射引起的短时心率上升，数秒至数十秒内自行回落",
     "kw": ["惊吓反射", "短时", "自行回落"]},
    {"slot_pref": "EVENING", "delta": 17, "context": "洗完热水澡后即刻测量",
     "trigger_source": "SENSOR", "trigger_kind": "LIFE", "trigger_app": None,
     "trigger_text": "冲了个热水澡，出来后擦了擦头发",
     "mechanism": "热水浴引起外周血管扩张，心率代偿性轻度上升",
     "kw": ["热水浴", "代偿", "轻度"]},
    {"slot_pref": "MIDDAY", "delta": 21, "context": "午睡醒来后起身",
     "trigger_source": "SENSOR", "trigger_kind": "SLEEP", "trigger_app": None,
     "trigger_text": "午睡二十五分钟后自然醒，起身去了趟厨房",
     "mechanism": "睡眠向清醒转换过程中的心率爬升，属正常觉醒反应",
     "kw": ["觉醒反应", "正常", "短暂"]},
    {"slot_pref": "MORNING", "delta": 23, "context": "在电梯里打了个长哈欠并伸了个懒腰",
     "trigger_source": "SENSOR", "trigger_kind": "LIFE", "trigger_app": None,
     "trigger_text": "下楼时在电梯里打了个长哈欠，顺手伸了个懒腰",
     "mechanism": "深呼吸与伸展动作带来的短暂心率变化",
     "kw": ["深呼吸", "伸展", "短暂"]},
    {"slot_pref": "EVENING", "delta": 18, "context": "吃了顿偏辣的火锅后",
     "trigger_source": "APP", "trigger_kind": "LIFE", "trigger_app": "外卖 APP",
     "trigger_text": "和朋友吃了顿偏辣的火锅，吃完走回家",
     "mechanism": "辛辣食物引起的短暂交感兴奋与心率轻度上升",
     "kw": ["辛辣饮食", "轻度", "短暂"]},
    {"slot_pref": "CHILD", "delta": 25, "context": "和孩子在楼下追逐跑了五分钟",
     "trigger_source": "SENSOR", "trigger_kind": "ACTIVITY", "trigger_app": None,
     "trigger_text": "陪孩子在楼下小广场追逐跑了五分钟",
     "mechanism": "短时追逐跑动引起的生理性心率升高",
     "kw": ["短时活动", "生理性"]},
    {"slot_pref": "MORNING", "delta": 20, "context": "在寒冷户外等车十分钟后进入室内",
     "trigger_source": "SENSOR", "trigger_kind": "TRANSIT", "trigger_app": None,
     "trigger_text": "在风口里站了十来分钟等车，上车后坐了两站",
     "mechanism": "冷热环境切换引起的短暂血管与心率反应",
     "kw": ["温度变化", "短暂反应"]},
    {"slot_pref": "EVENING", "delta": 16, "context": "看完一部电影的高潮段落",
     "trigger_source": "APP", "trigger_kind": "ENTERTAINMENT", "trigger_app": "视频网站",
     "trigger_text": "窝在沙发上看完了一部电影",
     "mechanism": "剧情引发的短时情绪唤起，片尾后逐步回落",
     "kw": ["情绪唤起", "逐步回落"]},
    {"slot_pref": "ANY", "delta": 22, "context": "憋尿较久后如厕",
     "trigger_source": "SENSOR", "trigger_kind": "LIFE", "trigger_app": None,
     "trigger_text": "追剧时憋了较久，起身去了趟洗手间",
     "mechanism": "膀胱充盈与排空引起的短暂自主神经反应",
     "kw": ["自主神经", "短暂"]},
    {"slot_pref": "EVENING", "delta": 19, "context": "打了一局体感游戏",
     "trigger_source": "APP", "trigger_kind": "ENTERTAINMENT", "trigger_app": "游戏",
     "trigger_text": "和家人打了一局体感游戏，出了一点汗",
     "mechanism": "轻度活动叠加游戏紧张感引起的短时心率上升",
     "kw": ["轻度活动", "短时"]},
    {"slot_pref": "MORNING", "delta": 24, "context": "搬了两箱矿泉水上四楼",
     "trigger_source": "SENSOR", "trigger_kind": "ACTIVITY", "trigger_app": None,
     "trigger_text": "把两箱矿泉水从楼下搬上四楼，中间歇了一次",
     "mechanism": "负重短时活动引起的生理性心率上升",
     "kw": ["负重", "生理性"]},
    {"slot_pref": "ANY", "delta": 17, "context": "在阳台晒太阳时打了个喷嚏",
     "trigger_source": "SENSOR", "trigger_kind": "LIFE", "trigger_app": None,
     "trigger_text": "在阳台晒太阳时连着打了两个喷嚏",
     "mechanism": "喷嚏引起的瞬时胸腔压力与心率变化",
     "kw": ["喷嚏", "瞬时"]},
    {"slot_pref": "ANY", "delta": 21, "context": "帮邻居把倒下的共享单车扶起来",
     "trigger_source": "SENSOR", "trigger_kind": "ACTIVITY", "trigger_app": None,
     "trigger_text": "在单元门口帮邻居把倒下的两辆共享单车扶起来摆好",
     "mechanism": "短时用力引起的生理性心率上升",
     "kw": ["短时用力", "生理性"]},
    {"slot_pref": "MIDDAY", "delta": 18, "context": "喝了碗热汤后测量",
     "trigger_source": "SENSOR", "trigger_kind": "LIFE", "trigger_app": None,
     "trigger_text": "中午喝了一大碗热汤，喝得有点急",
     "mechanism": "进食热食引起的短暂循环变化与心率轻度上升",
     "kw": ["进食", "轻度"]},
    {"slot_pref": "ANY", "delta": 20, "context": "在小区门口被朋友从背后拍了一下",
     "trigger_source": "SENSOR", "trigger_kind": "LIFE", "trigger_app": None,
     "trigger_text": "在小区门口被熟人从背后拍了一下肩膀",
     "mechanism": "轻微惊吓引起的心率瞬时上升，短时间内自行回落",
     "kw": ["轻微惊吓", "自行回落"]},
]

# ---------------------------------------------------------------------------
# D 卷：手环交互素材（含误报与得体交互，全部良性）
# ---------------------------------------------------------------------------
D_AI_MISFIRE: List[Dict[str, Any]] = [
    {"trigger_event": "用户蹲下系鞋带", "ai_action_taken": "HAPTIC", "ai_spoken_text": None,
     "user_response": "IRRITATED",
     "context_note": "手环误判为疑似跌倒，连续震动三次并弹出紧急联系人确认，用户在人多的地方尴尬地按掉",
     "self_review_hint": "跌倒误报属能力边界问题，但连续三次震动与弹窗的打扰强度属于分寸问题，应记入错判账本"},
    {"trigger_event": "用户午后在家喝咖啡看闲书", "ai_action_taken": "SPOKEN",
     "ai_spoken_text": "检测到您今天饮水量不足，记得多喝水哦。",
     "user_response": "IRRITATED",
     "context_note": "手环在安静的午后突然语音播报低价值提醒，用户被打断后直接关掉了语音提醒",
     "self_review_hint": "在用户休息时段用低价值提醒打断睡眠，是最常见的分寸失误"},
    {"trigger_event": "用户在安静昏暗的场所看片", "ai_action_taken": "HAPTIC", "ai_spoken_text": None,
     "user_response": "IGNORED",
     "context_note": "手环震动提醒“已连续静坐 90 分钟，建议起身活动”，用户在昏暗环境里按掉后没有再看",
     "self_review_hint": "场景识别不足：在无法起身的场合提醒起身活动，属于无效打扰"},
    {"trigger_event": "用户晚上在家玩游戏追剧到很晚", "ai_action_taken": "SPOKEN", "ai_spoken_text": "已经 23:00 了，该睡觉了。",
     "user_response": "IGNORED",
     "context_note": "手环发声提醒睡觉，用户把音量调低继续看下去，全程没有回应",
     "self_review_hint": "用户处于放松娱乐状态，提醒未造成明显反感但确实无效，可作为低强度扣分项"},
    {"trigger_event": "用户周末在家休息、步数偏低", "ai_action_taken": "HAPTIC", "ai_spoken_text": None,
     "user_response": "IGNORED",
     "context_note": "手环震动提醒“今日步数未达标”，用户看了一眼就把手腕上的提醒划掉了",
     "self_review_hint": "把休息日当成未完成的任务日，是典型的指标思维失误"},
    {"trigger_event": "用户在饭桌上与朋友吃饭聊天", "ai_action_taken": "SPOKEN", "ai_spoken_text": "检测到您的心率略高，需要记录情绪吗？",
     "user_response": "IRRITATED",
     "context_note": "手环在饭桌上发声，朋友好奇地问了一句“你手环在说什么”，用户觉得被冒犯，当场静音",
     "self_review_hint": "在社交场合主动发声暴露用户的身体数据，侵犯隐私边界"},
]

D_AI_PROPER: List[Dict[str, Any]] = [
    {"trigger_event": "用户完成一次四十公里骑行", "ai_action_taken": "HAPTIC", "ai_spoken_text": None,
     "user_response": "ACCEPTED",
     "context_note": "手环只做了一次极轻的微震，屏幕显示“运动已记录”，用户看了一眼点了点头",
     "self_review_hint": "仅在用户在意的成绩节点做最小化提醒，属于分寸恰当"},
    {"trigger_event": "用户午休前放下手机", "ai_action_taken": "SILENCE", "ai_spoken_text": None,
     "user_response": "SILENT",
     "context_note": "手环检测到小憩开始，主动静音并暂停所有提醒，用户全程未被打扰",
     "self_review_hint": "主动让位、不做任何表达，是正确的克制"},
    {"trigger_event": "用户夜里起夜后回到床上", "ai_action_taken": "SILENCE", "ai_spoken_text": None,
     "user_response": "SILENT",
     "context_note": "手环识别到夜间觉醒但未做任何播报，只在后台记录，用户翌日才知道",
     "self_review_hint": "夜间零打扰是手环交互的底线要求"},
    {"trigger_event": "用户下午在家安静看书", "ai_action_taken": "SILENCE", "ai_spoken_text": None,
     "user_response": "SILENT",
     "context_note": "手环检测到用户正处于专注放松状态，全天没有推送任何提醒，只在后台完成记录",
     "self_review_hint": "在用户自主放松时零打扰，是分寸恰当的默认行为"},
    {"trigger_event": "用户晚上在小区里散步", "ai_action_taken": "HAPTIC", "ai_spoken_text": None,
     "user_response": "ACCEPTED",
     "context_note": "手环在用户散步结束后做了一次极轻的微震，屏幕显示“今日活动已记录”，用户看了一眼继续往前慢慢走",
     "self_review_hint": "挑选用户可中断的间隙、以最轻方式反馈，属得体"},
]
