"""人设池：姓名、城市、职业、婚恋、防御习惯、家庭结构、固定压力、爱好、病史基线。

设计纪律：
- 职业必须自带真实的职场语境（上级称谓、工作对象、通勤方式），保证后续职场受挫场景可信；
- 病史基线必须写明“无器质性心脏病史”，这是反过度诊断红线的背景锚；
- 婚恋/家庭结构只写事实，不写“应该怎么想”，避免把结论喂给做题模型。
"""

from __future__ import annotations

from typing import Any, Dict, List

SURNAMES: List[str] = [
    "张", "王", "李", "赵", "陈", "刘", "杨", "黄", "周", "吴",
    "徐", "孙", "胡", "朱", "高", "林", "何", "郭", "马", "罗",
    "梁", "宋", "郑", "谢", "韩", "唐", "冯", "于", "董", "萧",
    "程", "曹", "袁", "邓", "许", "傅", "沈", "曾", "彭", "吕",
    "苏", "卢", "蒋", "蔡", "贾", "丁", "魏", "薛", "叶", "阎",
]

GIVEN_NAMES_MALE: List[str] = [
    "伟", "强", "磊", "军", "洋", "勇", "杰", "涛", "明", "超",
    "鹏", "斌", "波", "辉", "刚", "健", "峰", "亮", "宇", "浩",
    "睿", "一帆", "文轩", "致远", "嘉树", "砚舟", "知远", "亦辰", "书言", "怀瑾",
    "澈", "铖", "翊", "启", "晟", "慕白", "云舟", "август", "靖川", "望舒",
]

GIVEN_NAMES_FEMALE: List[str] = [
    "静", "敏", "燕", "娟", "丽", "娜", "芳", "霞", "婷", "雪",
    "琳", "倩", "颖", "萍", "玲", "洁", "梅", "悦", "珊", "露",
    "瑾瑜", "语棠", "若彤", "温言", "书瑶", "映雪", "知夏", "之桃", "沁悠", "念禾",
    "婉宁", "宜臻", "岑", "昀", "昭", "夏菡", "云舒", "雨眠", "斯羽", "折玉",
]

CITIES: List[Dict[str, Any]] = [
    {"name": "北京", "tier": "一线"},
    {"name": "上海", "tier": "一线"},
    {"name": "深圳", "tier": "一线"},
    {"name": "广州", "tier": "一线"},
    {"name": "杭州", "tier": "新一线"},
    {"name": "成都", "tier": "新一线"},
    {"name": "武汉", "tier": "新一线"},
    {"name": "西安", "tier": "新一线"},
    {"name": "南京", "tier": "新一线"},
    {"name": "苏州", "tier": "新一线"},
    {"name": "重庆", "tier": "新一线"},
    {"name": "长沙", "tier": "新一线"},
    {"name": "郑州", "tier": "新一线"},
    {"name": "青岛", "tier": "新一线"},
    {"name": "天津", "tier": "新一线"},
    {"name": "合肥", "tier": "新一线"},
    {"name": "宁波", "tier": "二线"},
    {"name": "无锡", "tier": "二线"},
    {"name": "佛山", "tier": "二线"},
    {"name": "福州", "tier": "二线"},
    {"name": "济南", "tier": "二线"},
    {"name": "厦门", "tier": "二线"},
    {"name": "昆明", "tier": "二线"},
    {"name": "大连", "tier": "二线"},
    {"name": "南昌", "tier": "二线"},
    {"name": "贵阳", "tier": "二线"},
    {"name": "石家庄", "tier": "二线"},
    {"name": "南宁", "tier": "二线"},
    {"name": "温州", "tier": "二线"},
    {"name": "常州", "tier": "二线"},
    {"name": "徐州", "tier": "三线"},
    {"name": "洛阳", "tier": "三线"},
    {"name": "烟台", "tier": "三线"},
    {"name": "扬州", "tier": "三线"},
    {"name": "绍兴", "tier": "三线"},
    {"name": "中山", "tier": "三线"},
    {"name": "珠海", "tier": "三线"},
    {"name": "汕头", "tier": "三线"},
    {"name": "保定", "tier": "三线"},
    {"name": "绵阳", "tier": "三线"},
    {"name": "桂林", "tier": "三线"},
    {"name": "芜湖", "tier": "三线"},
]

# 职业：income 单位为“千元/月”区间；workplace 供职场场景使用；commute 供通勤切片使用
OCCUPATIONS: List[Dict[str, Any]] = [
    {"name": "互联网后端架构师", "income": (22, 45), "workplace": "开放式办公区", "boss": "技术总监",
     "peer": "同组后端同事", "obj": "微服务架构方案", "commute": "地铁通勤", "night": True},
    {"name": "三甲医院麻醉科主治医师", "income": (18, 32), "workplace": "手术室准备间", "boss": "科室主任",
     "peer": "同台麻醉护士", "obj": "次日手术麻醉方案", "commute": "自驾通勤", "night": True},
    {"name": "城商行对公客户经理", "income": (12, 26), "workplace": "营业部洽谈室", "boss": "支行行长",
     "peer": "信贷同事", "obj": "季度对公存款指标", "commute": "地铁通勤", "night": False},
    {"name": "初中语文教师兼班主任", "income": (7, 13), "workplace": "年级组办公室", "boss": "年级组长",
     "peer": "搭班数学老师", "obj": "期末考试班级平均分", "commute": "公交通勤", "night": False},
    {"name": "汽车零部件销售经理", "income": (9, 22), "workplace": "客户会议室", "boss": "销售总监",
     "peer": "同区域销售", "obj": "年度框架合同报价", "commute": "自驾通勤", "night": False},
    {"name": "纪录片剪辑师", "income": (10, 20), "workplace": "后期机房", "boss": "总编导",
     "peer": "同期剪辑师", "obj": "第二集粗剪版本", "commute": "骑行通勤", "night": True},
    {"name": "建筑工地项目经理", "income": (14, 28), "workplace": "项目现场会议室", "boss": "总包负责人",
     "peer": "现场施工员", "obj": "主体结构验收资料", "commute": "自驾通勤", "night": True},
    {"name": "连锁餐饮门店店长", "income": (8, 15), "workplace": "门店后厨通道", "boss": "区域督导",
     "peer": "值班店员", "obj": "本月门店营业额", "commute": "步行通勤", "night": True},
    {"name": "小型律所执业律师", "income": (10, 40), "workplace": "律所会议室", "boss": "高级合伙人",
     "peer": "同所授薪律师", "obj": "当事人股权纠纷案卷", "commute": "地铁通勤", "night": True},
    {"name": "电商平台运营主管", "income": (12, 24), "workplace": "运营作战室", "boss": "运营总监",
     "peer": "类目运营", "obj": "大促活动排期", "commute": "地铁通勤", "night": True},
    {"name": "国有银行网点柜员", "income": (6, 11), "workplace": "网点现金区", "boss": "网点主任",
     "peer": "当班同事", "obj": "季末揽储任务", "commute": "公交通勤", "night": False},
    {"name": "跨境电商独立站卖家", "income": (8, 45), "workplace": "自家工作室", "boss": "海外客户",
     "peer": "合作买手", "obj": "旺季备货计划", "commute": "居家办公", "night": True},
    {"name": "公立小学英语教师", "income": (6, 11), "workplace": "教师办公室", "boss": "教导主任",
     "peer": "同年组老师", "obj": "校级公开课教案", "commute": "电动车通勤", "night": False},
    {"name": "基层派出所社区民警", "income": (7, 13), "workplace": "所内值班室", "boss": "带班副所长",
     "peer": "同班辅警", "obj": "辖区矛盾调解台账", "commute": "步行通勤", "night": True},
    {"name": "三甲医院急诊科护士", "income": (8, 15), "workplace": "急诊抢救区", "boss": "护士长",
     "peer": "搭班同事", "obj": "留观病人交接记录", "commute": "地铁通勤", "night": True},
    {"name": "芯片封装工艺工程师", "income": (18, 34), "workplace": "洁净车间外办公区", "boss": "工艺组长",
     "peer": "设备工程师", "obj": "良率异常分析报告", "commute": "厂车通勤", "night": True},
    {"name": "轨道交通信号检修工", "income": (7, 12), "workplace": "车辆段检修库", "boss": "工班长",
     "peer": "同班组员", "obj": "道岔信号联锁测试", "commute": "班车通勤", "night": True},
    {"name": "社区医院全科医生", "income": (8, 16), "workplace": "诊室走廊", "boss": "中心副主任",
     "peer": "公卫科同事", "obj": "慢病随访表", "commute": "骑行通勤", "night": False},
    {"name": "装修公司设计总监", "income": (15, 35), "workplace": "材料展厅", "boss": "公司老板",
     "peer": "主案设计师", "obj": "别墅项目全案图纸", "commute": "自驾通勤", "night": True},
    {"name": "民航乘务长", "income": (12, 22), "workplace": "客舱服务间", "boss": "客舱经理",
     "peer": "同机组成员", "obj": "航班服务整改单", "commute": "机组车通勤", "night": True},
    {"name": "互联网大厂产品经理", "income": (25, 50), "workplace": "会议室", "boss": "业务线负责人",
     "peer": "研发对接人", "obj": "年度版本路线图", "commute": "地铁通勤", "night": True},
    {"name": "幼儿园大班主班老师", "income": (5, 9), "workplace": "班级活动室", "boss": "园长",
     "peer": "配班老师", "obj": "期末家园联系册", "commute": "电动车通勤", "night": False},
    {"name": "国有电网运维调度员", "income": (12, 20), "workplace": "调度大厅", "boss": "值班长",
     "peer": "同值调度员", "obj": "迎峰度夏负荷曲线", "commute": "自驾通勤", "night": True},
    {"name": "生鲜超市采购主管", "income": (9, 18), "workplace": "批发市场档口", "boss": "采购总监",
     "peer": "品类采购", "obj": "春节前备货清单", "commute": "自驾通勤", "night": False},
    {"name": "自由摄影师", "income": (6, 30), "workplace": "客户拍摄现场", "boss": "品牌方市场负责人",
     "peer": "助理", "obj": "婚礼跟拍成片", "commute": "自驾通勤", "night": False},
    {"name": "高职院校辅导员", "income": (7, 12), "workplace": "学工办公室", "boss": "学生处副处长",
     "peer": "同院系辅导员", "obj": "学生心理危机台账", "commute": "公交通勤", "night": False},
    {"name": "医疗器械售后工程师", "income": (10, 20), "workplace": "医院设备科", "boss": "售后主管",
     "peer": "服务同事", "obj": "设备巡检工单", "commute": "高铁出差", "night": True},
    {"name": "出版社图书编辑", "income": (7, 14), "workplace": "编辑室", "boss": "编辑部主任",
     "peer": "同室编辑", "obj": "重点书目三审稿", "commute": "地铁通勤", "night": False},
    {"name": "物流园区调度主管", "income": (8, 16), "workplace": "分拨中心现场", "boss": "运营经理",
     "peer": "场站调度员", "obj": "双十一运力预案", "commute": "自驾通勤", "night": True},
    {"name": "口腔科执业医师", "income": (15, 40), "workplace": "诊室", "boss": "诊所合伙人",
     "peer": "护士", "obj": "种植牙手术排期", "commute": "自驾通勤", "night": False},
    {"name": "小学体育教师", "income": (6, 10), "workplace": "操场器材室", "boss": "体育教研组长",
     "peer": "同组教师", "obj": "校运动会秩序册", "commute": "骑行通勤", "night": False},
    {"name": "财务共享中心总账会计", "income": (9, 18), "workplace": "财务共享办公区", "boss": "财务经理",
     "peer": "同组会计", "obj": "季度合并报表", "commute": "地铁通勤", "night": True},
    {"name": "物业服务项目经理", "income": (8, 16), "workplace": "物业服务中心", "boss": "区域总",
     "peer": "秩序主管", "obj": "业主满意度整改方案", "commute": "公交通勤", "night": True},
    {"name": "国营施工图结构设计师", "income": (12, 24), "workplace": "设计院工位", "boss": "专业负责人",
     "peer": "同专业同事", "obj": "超限审查回复单", "commute": "地铁通勤", "night": True},
    {"name": "殡葬礼仪服务师", "income": (7, 15), "workplace": "殡仪馆接待厅", "boss": "服务部主管",
     "peer": "同事", "obj": "次日告别仪式流程", "commute": "自驾通勤", "night": True},
    {"name": "宠物医院执业兽医师", "income": (10, 22), "workplace": "诊疗室", "boss": "院长",
     "peer": "护理师", "obj": "疑难病例手术方案", "commute": "自驾通勤", "night": True},
    {"name": "地铁站值班站长", "income": (6, 11), "workplace": "车站控制室", "boss": "中心站站长",
     "peer": "值班员", "obj": "客流疏导预案", "commute": "地铁通勤", "night": True},
    {"name": "软件外包交付项目经理", "income": (14, 26), "workplace": "客户方驻场办公区", "boss": "甲方项目经理",
     "peer": "外包团队成员", "obj": "里程碑交付验收单", "commute": "地铁通勤", "night": True},
    {"name": "区级机关综合科科员", "income": (8, 13), "workplace": "机关办公楼", "boss": "科长",
     "peer": "同科室同事", "obj": "年度考核材料", "commute": "公交通勤", "night": True},
    {"name": "健身工作室私教", "income": (7, 20), "workplace": "训练区", "boss": "工作室老板",
     "peer": "前台同事", "obj": "会员续课率", "commute": "电动车通勤", "night": True},
    {"name": "初中化学教师", "income": (7, 12), "workplace": "实验室", "boss": "教研组长",
     "peer": "同组教师", "obj": "实验安全规范", "commute": "公交通勤", "night": False},
    {"name": "半导体测试工程师", "income": (16, 30), "workplace": "测试车间外办公室", "boss": "测试经理",
     "peer": "测试同事", "obj": "测试程式优化报告", "commute": "厂车通勤", "night": True},
    {"name": "三甲医院放射科技师", "income": (9, 16), "workplace": "CT 机房", "boss": "技师长",
     "peer": "当班技师", "obj": "预约排程优化", "commute": "地铁通勤", "night": True},
    {"name": "文旅项目策划", "income": (9, 18), "workplace": "策划部", "boss": "项目总监",
     "peer": "策划同事", "obj": "古镇夜游方案", "commute": "地铁通勤", "night": True},
    {"name": "二手房产经纪人", "income": (5, 35), "workplace": "门店", "boss": "门店店长",
     "peer": "同组经纪人", "obj": "本月带看转化率", "commute": "电动车通勤", "night": True},
    {"name": "互联网数据分析师", "income": (18, 32), "workplace": "数据团队工位", "boss": "数据总监",
     "peer": "分析同事", "obj": "用户留存归因报告", "commute": "地铁通勤", "night": True},
    {"name": "国企宣传干事", "income": (8, 14), "workplace": "宣传部门办公室", "boss": "宣传部长",
     "peer": "同部门同事", "obj": "年中工作综述稿", "commute": "公交通勤", "night": False},
    {"name": "乡镇卫生院公卫医师", "income": (5, 9), "workplace": "卫生院门诊", "boss": "院长",
     "peer": "村医", "obj": "老年人健康体检率", "commute": "自驾通勤", "night": False},
    {"name": "服装厂版房主管", "income": (9, 18), "workplace": "版房", "boss": "生产厂长",
     "peer": "版师", "obj": "秋冬款样衣工艺单", "commute": "电动车通勤", "night": True},
    {"name": "游戏公司数值策划", "income": (16, 32), "workplace": "开放工位", "boss": "主策划",
     "peer": "系统策划", "obj": "新赛季平衡性方案", "commute": "地铁通勤", "night": True},
    {"name": "高校实验员", "income": (8, 14), "workplace": "实验室", "boss": "课题组教授",
     "peer": "同课题组助理", "obj": "细胞实验数据", "commute": "校车通勤", "night": True},
    {"name": "连锁药房执业药师", "income": (7, 13), "workplace": "药房柜台", "boss": "门店经理",
     "peer": "店员", "obj": "处方药销售合规自查", "commute": "电动车通勤", "night": False},
    {"name": "家具厂数控开料工", "income": (7, 14), "workplace": "生产车间", "boss": "车间主任",
     "peer": "同班组员", "obj": "定制订单排产单", "commute": "电动车通勤", "night": True},
    {"name": "城市环卫片区班长", "income": (4, 7), "workplace": "环卫驿站", "boss": "环卫所所长",
     "peer": "保洁员", "obj": "创城迎检保洁方案", "commute": "电动车通勤", "night": True},
    {"name": "人民法院书记员", "income": (8, 14), "workplace": "审判庭办公区", "boss": "承办法官",
     "peer": "同庭书记员", "obj": "庭审笔录与卷宗归档", "commune": "公交通勤", "commute": "公交通勤", "night": True},
    {"name": "有机农场主理人", "income": (6, 25), "workplace": "大棚与田埂", "boss": "合作社交付负责人",
     "peer": "农工", "obj": "会员蔬菜订单", "commute": "自驾通勤", "night": False},
    {"name": "电梯维保技师", "income": (8, 15), "workplace": "楼宇机房", "boss": "维保站长",
     "peer": "同组技师", "obj": "年检整改工单", "commute": "电动车通勤", "night": True},
    {"name": "城市综合体招商主管", "income": (12, 26), "workplace": "招商中心", "boss": "招商总监",
     "peer": "招商专员", "obj": "主力店签约进度", "commute": "地铁通勤", "night": True},
    {"name": "中职学校汽修实训教师", "income": (7, 12), "workplace": "实训车间", "boss": "实训处主任",
     "peer": "实训教师", "obj": "技能大赛集训方案", "commute": "自驾通勤", "night": False},
    {"name": "银行总行风险审查岗", "income": (20, 35), "workplace": "授信审查室", "boss": "审查部总经理",
     "peer": "同岗审查员", "obj": "大额授信审查意见", "commute": "地铁通勤", "night": True},
    {"name": "地方融媒体中心记者", "income": (6, 12), "workplace": "采编大厅", "boss": "新闻部主任",
     "peer": "摄像记者", "obj": "老旧小区改造专题报道", "commute": "自驾通勤", "night": True},
    {"name": "养老机构护理主管", "income": (7, 13), "workplace": "护理楼层", "boss": "院长",
     "peer": "护理组长", "obj": "家属沟通台账", "commute": "公交通勤", "night": True},
    {"name": "五金厂车间班组长", "income": (6, 11), "workplace": "冲压车间", "boss": "生产主管",
     "peer": "班组工人", "obj": "不良品率整改单", "commute": "电动车通勤", "night": True},
    {"name": "英语同声传译", "income": (20, 60), "workplace": "同传间", "boss": "会务项目经理",
     "peer": "搭档译员", "obj": "行业峰会双语术语表", "commute": "高铁出差", "night": False},
    {"name": "档案数字化项目经理", "income": (10, 18), "workplace": "档案馆扫描间", "boss": "甲方主管",
     "peer": "项目成员", "obj": "档案数字化验收清单", "commute": "公交通勤", "night": False},
    {"name": "社区咖啡店店主", "income": (5, 18), "workplace": "门店吧台", "boss": "片区经理",
     "peer": "兼职店员", "obj": "日均杯量与房租", "commute": "步行通勤", "night": False},
    {"name": "自由插画师", "income": (6, 30), "workplace": "家中画室", "boss": "甲方客户",
     "peer": "同行画友", "obj": "约稿稿件与商单排期", "commute": "居家办公", "night": True},
    {"name": "货运司机", "income": (8, 15), "workplace": "长途货车驾驶室", "boss": "车队调度",
     "peer": "同线司机", "obj": "跨省货运单与限行时段", "commute": "自驾通勤", "night": True},
]

# 婚恋状态（single=True 表示当前无稳定亲密关系，家庭类事件会相应降权）
RELATIONSHIPS: List[Dict[str, Any]] = [
    {"text": "单身（分手 4 个月，尚未走出来）", "single": True, "has_child": False},
    {"text": "单身（长期不婚倾向，与父母因此长期冷战）", "single": True, "has_child": False},
    {"text": "恋爱中（同居 3 年，尚未领证）", "single": False, "has_child": False},
    {"text": "恋爱中（刚订婚，对方家里提出 18.8 万彩礼）", "single": False, "has_child": False},
    {"text": "已婚 2 年（异地，一周见一次）", "single": False, "has_child": False},
    {"text": "已婚 11 年（二胎待产中）", "single": False, "has_child": True},
    {"text": "已婚 6 年（孩子 4 岁，双方父母轮流带）", "single": False, "has_child": True},
    {"text": "已婚 15 年（配偶长期在外地工作）", "single": False, "has_child": True},
    {"text": "离婚 1 年（孩子抚养权在对方，每月探视一次）", "single": True, "has_child": True},
    {"text": "恋爱中（伴侣在读研，两人靠周末维系）", "single": False, "has_child": False},
    {"text": "已婚 8 年（配偶刚失业，家庭开支全压在一人身上）", "single": False, "has_child": True},
    {"text": "单亲抚养（孩子 6 岁，父母在老家无法帮忙）", "single": True, "has_child": True},
    {"text": "已婚 3 年（与长辈同住，生活中摩擦不断）", "single": False, "has_child": False},
    {"text": "恋爱中（对方父母明确反对，嫌其家境）", "single": False, "has_child": False},
    {"text": "已婚 5 年（房贷与装修贷并行，双职工）", "single": False, "has_child": True},
    {"text": "恋爱中（异地两年，每周高铁往返）", "single": False, "has_child": False},
    {"text": "已婚 1 年（新婚，双方父母催生育）", "single": False, "has_child": False},
    {"text": "离婚 3 年（独居，与前配偶因抚养费偶有争执）", "single": True, "has_child": True},
    {"text": "恋爱中（刚在一起半年，对方是同事）", "single": False, "has_child": False},
    {"text": "已婚 20 年（孩子刚高考完，夫妻共同话题变少）", "single": False, "has_child": True},
    {"text": "单身（与父母同住，被反复催婚）", "single": True, "has_child": False},
    {"text": "已婚 4 年（夫妻共同还贷，暂无生育计划）", "single": False, "has_child": False},
    {"text": "恋爱中（刚进入冷静期，关系尚未彻底了断）", "single": False, "has_child": False},
    {"text": "已婚 9 年（配偶身患慢性病，长期承担照护）", "single": False, "has_child": True},
]

# 防御习惯：不写“好/坏”，只写行为模式，供答卷自行判断
DEFENSE_HABITS: List[str] = [
    "内敛隐忍，习惯用理性逻辑消化情绪",
    "用高糖外卖和熬夜短视频麻痹自己",
    "拼命加班，把工作当情绪避难所",
    "习惯把情绪写成文字但不发出去",
    "深夜独自出门长走，从不告诉任何人",
    "对家人报喜不报忧，永远只说“挺好的”",
    "表面顺从、内心记账，从不正面冲突",
    "习惯性道歉，把责任先揽到自己身上",
    "用玩笑和自嘲带过所有委屈",
    "把所有事提前规划好，靠清单获得安全感",
    "遇到冲突第一时间找好友倾诉",
    "靠运动硬扛，用身体疲惫换脑子安静",
    "习惯在深夜复盘每一句对话哪里说错了",
    "把委屈咽回去，第二天照常上班",
    "沉迷手工或修理，靠动手转移注意力",
    "反复刷同一段聊天记录与相册",
    "用理财 APP 反复核算数字来获得掌控感",
    "强撑体面，绝不在外人面前流露情绪",
    "转移注意力式忙碌，用家务填满时间",
    "习惯自我否定，总觉得是自己不够好",
]

FAMILY_STRUCTURES: List[str] = [
    "老家县城，父母退休在家，独生子女",
    "老家农村，父亲务农母亲操持家务，有一个已出嫁的姐姐",
    "父母早年离异，随母亲长大，与父亲几乎不联系",
    "父母在老家经营小超市，身体尚可但不愿体检",
    "家中长子/长女，弟妹尚在读书，学费由本人补贴",
    "双亲随迁同住帮忙带孩子，两代人生活习惯冲突明显",
    "父亲三年前中风后遗症，母亲独自照护，本人每月寄钱",
    "伴侣是独生女，双方四位老人均在同一城市",
    "伴侣的父母在老家，逢年过节必须回乡，来回两天车程",
    "父母在东北老家，自己在南方工作，一年回一次",
    "母亲独居老家，每天固定通一次电话才安心",
    "父亲刚退休，被返聘继续上班，母亲希望本人常回家",
]

FIXED_PRESSURES: List[str] = [
    "房贷每月 8900，剩余 22 年",
    "房租每月 4200，房东已通知下季度涨价",
    "车贷每月 3200，明年 3 月还清",
    "孩子国际幼儿园每月 6800",
    "老家父母看病长期用药，每月固定寄回 3000",
    "父亲去年手术借的 8 万尚未还清",
    "装修贷每月 2600，还有 18 期",
    "弟弟在读大学的学费与生活费由本人承担",
    "配偶失业 5 个月，家庭开支全靠一人",
    "信用卡分期与消费贷合计每月 5400",
    "刚在老家县城付了首付，月供占收入六成",
    "公司连续两个季度绩效打折，收入缩水三成",
    "母亲长期吃降压药，定期复查费用不小",
    "与朋友合伙开店，亏损还需继续垫资",
    "每月固定给父母 2000 养老钱，不敢断",
    "刚给父亲换了助听器，存款见底",
    "老家房子要翻修，亲戚凑的钱有一半靠本人",
    "在异地租房+还老家房贷，两份月供并行",
]

HOBBIES: List[str] = [
    "夜跑", "手冲咖啡", "城郊徒步", "拼装模型", "弹吉他", "刷算法题", "写钢笔字",
    "做手账", "养多肉", "烘焙", "摄影", "游泳", "羽毛球", "读历史书", "看纪录片",
    "打《原神》", "拼高达", "钓鱼", "骑行", "做木工", "练琴", "学日语", "养猫",
    "养狗", "看球赛", "做饭", "集邮", "跳爵士舞", "练拳击", "研究古典密码学",
    "缝纫改造旧衣", "种菜", "看话剧", "玩桌游", "剪视频", "修旧家电", "练书法",
    "爬山", "学做甜品", "收藏模型枪",
]

MEDICAL_BASELINES: List[str] = [
    "体检无器质性心脏病史，血压 118/76，静息心电图正常，医生只提过“压力大注意休息”",
    "无心血管基础病，去年体检报告仅显示轻度脂肪肝，医嘱控制饮食",
    "体检无异常，家族无心脏病史，唯一直系亲属高血压为 60 岁后发病",
    "无器质性心脏病史，有季节性过敏性鼻炎，长期伏案致颈椎轻度劳损",
    "体检未见器质性异常，血常规与甲功均正常，医生提示睡眠不足",
    "无重大病史，去年做过 24 小时动态心电图，结论为“窦性心律，未见异常”",
    "无心脏基础病，既往仅有过一次运动后胸闷，检查后排除器质性问题",
    "体检正常，唯血脂略高，医生建议运动与控糖，未开药",
    "无器质性疾病，长期肠胃敏感，情绪紧张时易胃部不适",
    "无心脏病史，家族中无猝死病例，最近一次体检为半年前，各项指标正常",
    "无基础疾病，唯一问题是慢性失眠，未服用过助眠药物",
    "体检无器质性异常，心电图正常，医生记录“患者自述工作压力较大”",
]
