"""Build the M0' (V3.0.1) contract-extension frozen snapshot.

R2 freeze (schemas/r2/m0_contract_snapshot.json) is NEVER regenerated by this
tool; the R2 gate keeps its byte-identical baseline. The V3.0.1 snapshot
covers the extension surface only (enums_v3, models_v3, services/state_machines_v3)
so the two freeze lines evolve independently and can both be CI-gated.

Usage:
    python tools/governance/build_v3p1_snapshot.py --check   # CI: fail if drifted
    python tools/governance/build_v3p1_snapshot.py --write   # governance-approved refresh
"""

from __future__ import annotations

import argparse
import hashlib
import inspect
import json
import sys
from enum import Enum
from pathlib import Path

from pydantic import BaseModel

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT / "src"))

from aios_core.contracts import enums_v3, models_v3  # noqa: E402
from aios_core.services import state_machines_v3  # noqa: E402

SNAPSHOT_PATH = ROOT / "schemas" / "v3p1" / "m0p_contract_snapshot.json"
GATE_VERSION = "M0P-V3.0.1"


def _schema_hash(model: type[BaseModel]) -> str:
    schema = model.model_json_schema()
    canonical = json.dumps(
        schema, ensure_ascii=False, sort_keys=True, separators=(",", ":")
    ).encode("utf-8")
    return hashlib.sha256(canonical).hexdigest()


def _model_hashes() -> dict[str, str]:
    result: dict[str, str] = {}
    for name, value in inspect.getmembers(models_v3, inspect.isclass):
        if value.__module__ != models_v3.__name__:
            continue
        if not issubclass(value, BaseModel):
            continue
        result[f"{models_v3.__name__}.{name}"] = _schema_hash(value)
    return dict(sorted(result.items()))


def _enum_values() -> dict[str, list[str]]:
    result: dict[str, list[str]] = {}
    for name, value in inspect.getmembers(enums_v3, inspect.isclass):
        if value.__module__ != enums_v3.__name__:
            continue
        if not issubclass(value, Enum):
            continue
        result[f"{enums_v3.__name__}.{name}"] = [item.value for item in value]
    return dict(sorted(result.items()))


def _transitions() -> dict[str, dict[str, list[str]]]:
    spec = {
        "prediction": (
            state_machines_v3.allowed_prediction_transitions,
            __import__("aios_core.contracts.enums_v3", fromlist=["PredictionStatus"]).PredictionStatus,
        ),
        "life_chapter": (
            state_machines_v3.allowed_chapter_transitions,
            __import__("aios_core.contracts.enums_v3", fromlist=["LifeChapterStatus"]).LifeChapterStatus,
        ),
        "epoch": (
            state_machines_v3.allowed_epoch_transitions,
            __import__("aios_core.contracts.enums_v3", fromlist=["EpochState"]).EpochState,
        ),
        "speaker_cluster": (
            state_machines_v3.allowed_cluster_transitions,
            __import__("aios_core.contracts.enums_v3", fromlist=["SpeakerClusterStatus"]).SpeakerClusterStatus,
        ),
        "tombstone": (
            state_machines_v3.allowed_tombstone_transitions,
            __import__("aios_core.contracts.enums_v3", fromlist=["TombstoneStage"]).TombstoneStage,
        ),
    }
    out: dict[str, dict[str, list[str]]] = {}
    for name, (fn, enum_cls) in spec.items():
        out[name] = {
            state.value: sorted(t.value for t in fn(state)) for state in enum_cls
        }
    return out


def build_current_snapshot() -> dict[str, object]:
    return {
        "gate_version": GATE_VERSION,
        "models": _model_hashes(),
        "enums": _enum_values(),
        "transitions": _transitions(),
    }


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--write", action="store_true")
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    current = build_current_snapshot()
    rendered = json.dumps(current, ensure_ascii=False, indent=2, sort_keys=True) + "\n"
    if args.write:
        SNAPSHOT_PATH.parent.mkdir(parents=True, exist_ok=True)
        SNAPSHOT_PATH.write_text(rendered, encoding="utf-8")
        print(f"wrote {SNAPSHOT_PATH}")
        return 0
    if args.check:
        if not SNAPSHOT_PATH.exists():
            print("no frozen v3p1 snapshot found; run with --write under governance")
            return 1
        expected = json.loads(SNAPSHOT_PATH.read_text(encoding="utf-8"))
        if expected != current:
            print("V3.0.1 contract extension drifted vs frozen snapshot")
            return 2
        print("v3p1 snapshot frozen & matching")
        return 0
    print(rendered, end="")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
